### ISSUE TITLE
User menu's profile is not loading on first time

### ISSUE THREAD

**Issue by Roman-Skripka** [adobe/asset-share-commons#1000]
**Describe the bug**
Login into ASC using LDAP.

**Environment**
* AEM Version: 6.5.17
* Asset Share Commons Version: 3.3.0
* Checked on Publish

**To Reproduce**
1. Login into ASC using LDAP.
2. See the broken user info section

**Expected behavior**
User info is rendered properly

**Screenshots**
![image](https://github.com/adobe/asset-share-commons/assets/7115589/5147287d-8375-4992-8bda-68166bed40c5)

**Additional context**
It loads correctly on page refresh

**Comment by davidjgonzalez** [comment]
Fixed via: https://github.com/adobe/asset-share-commons/pull/1001
