### ISSUE TITLE
Help with DownloadExtensionResolver in local SDK

### ISSUE THREAD

**Issue by mgurney-leappoint** [adobe/asset-share-commons#1008]
Hi,

I have been reviewing the ticket ".MOV asset is being downloaded as .QT #991" and trying to implement this on my local SDK environment for application/postscript files that are being downloaded as .ai instead of .eps files.

Does this only work on AEMaaCS or can i test it locally ?

I am not sure on where to put the code as the example in the ticket shows a custom implementation of DownloadExtensionResolver.java, but when i am not sure what i need to put in here and if this is the right file to specify the mime type etc.

I need something like this

if ("application/postscript".equals(assetRendition.getMimeType())) {
                return "eps";
             }

I have the latest version of ASC 3.4.0 installed and running, any help would be greatly appreciated.

**Comment by davidjgonzalez** [comment]
Hi @mgurney-leappoint  - yes! this should work locally. This is invoked in the via the ExpressionDownloadArchiveNamer [1] which is used "everywhere" where a zip is created.

1. You should have your own AEM Maven project that embeds ASC (thats how ASC gets deployed)
2. In that AEM Maven project, you should have a `core` project that contains your project's OSGi bundle (java code).
3. You would put your custom `DownloadExtensionResolverImpl.java` that implements `DownloadExtensionResolver` in that project as you would any other OSGi Service implementation.

Let me know if that makes sense, or if youre missing something in step 1 or 2.



[1] ]https://github.com/adobe/asset-share-commons/blob/main/core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/ExpressionDownloadArchiveNamer.java

**Comment by davidjgonzalez** [comment]
Closing - please open if you continue to have questions.
