### ISSUE TITLE
Every download happens as zip

### ISSUE THREAD

**Issue by RahulMohann** [adobe/asset-share-commons#1009]
Hi,

Every download in ASC is resulting into a zip package. Even if I'm just downloading a 1MB asset using the download option in the asset card, it still downloads as a zip package. Can we change this behavior to just download the asset directly? How can we change it?

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
Sure, you could add the following JS to your project.. What this does is adds a submit handler to the download-modal form, that checks if: 

1. Only 1 asset is selected
1. Only 1 rendition is selected

And if this is the case, updates the form to make  a request for that asset + asset rendition URL.

```
document.body.addEventListener('submit', (e) => {
    if (e.target?.matches('[data-asset-share-id="download-modal"]')) {
        let form = e.target;

        let renditionName = [...form.querySelectorAll('input[type="checkbox"][name="renditionName"]:checked')].map((checkbox) => { return checkbox.value; });
        let assetPath = [...form.querySelectorAll('input[name="path"]')].map((input) => { return input.value; });

        if (renditionName.length === 1 && assetPath.length === 1) {
            // HTTP GEt <absolute asset path>.renditions/<rendition name>/download/asset.rendition
            form.method = 'GET';
            form.action = `${assetPath[0]}.renditions/${renditionName}/download/asset.rendition`;
            console.log(form.action);
            debugger;
        } else {
            console.log('downloading zip');
        }
    }
});
```

**Comment by davidjgonzalez** [comment]
Please re-open if this doesnt solve your problem!

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez , Could you please be a little more specific on where exactly to add this JS to? Sorry, if I'm missing something.

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
@RahulMohann add it one of the clientlibs you load on your ASC pages.

If you dont already have your own clientlib your adding on your ASC pages, you can make a new one, set the category to `asset-share-commons.site` and add this JS snippet to that -- and that will get loaded on the ASC pages.

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez ,

Thanks a lot for the update. I was able to add the code snippet to the client lib and is loaded with the page. However, can I use the same logic in the download action available in the cards or in the detail pages with the direct download enabled?

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
@RahulMohann i think direct downloads trigger a submit action on the form, so i think it should work - but youd have to try it out as im not 100% sure on the timing w/ the modal being available to the document scope.

Have you tried it? if its going to work - it will just work.

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez ,

I've tried it with direct download enabled. It's not triggering the submit action on the form. I think the modal is not in the document scope for the direct downloads. I've tried something like the below instead. Not sure if it's an optimal way to do this. With this, the original rendition is getting downloaded. Also I haven't selected any of the renditions in the download modal configuration. Could you please let me know if this will cause any other issues?

Requirement is just to download the original files through ASC and no renditions.

document.body.addEventListener('click', (e) => {
    if (e.target?.matches('[data-asset-share-id="download-asset"]')) {
        e.preventDefault();
        let assetPathNew = e.target?.getAttribute('data-asset-share-asset');
        if (assetPathNew != null) {            
            document.location.href=`${assetPathNew}.renditions/original/download/asset.rendition`;            
        } else {
            console.log('downloading zip');
        }
    }
});

Thanks,
Rahul

**Comment by RahulMohann** [comment]
And it's a custom client library, which we can take it off if needed to enable the normal zipped downloads back.

**Comment by davidjgonzalez** [comment]
Yup! This works assuming you aren't using licensed assets (which pops up the license agreement before download!)

**Comment by RahulMohann** [comment]
Not as of now. Thank you @davidjgonzalez !

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez , Sorry to open this topic again. I tried the below code and it works fine with the download function available in the card in search page and in the asset detail page. But then we found that the download cart is not working. Inorder to make the below code work, I had to enable the direct download with no default download options selected. And that stops the download functionality in cart.

document.body.addEventListener('click', (e) => {
if (e.target?.matches('[data-asset-share-id="download-asset"]')) {
e.preventDefault();
let assetPathNew = e.target?.getAttribute('data-asset-share-asset');
if (assetPathNew != null) {
document.location.href=${assetPathNew}.renditions/original/download/asset.rendition;
} else {
console.log('downloading zip');
}
}
});

And I tried the original code you provided with direct download disabled.  Even that's also not working and it still download as zip. I think overwriting the action in the client side is not really working. Could you please check once and suggest any solutions for this?

Thanks,
Rahul

**Comment by RahulMohann** [comment]
![Uploading Download-clientlib-invoked.PNG…]()

**Comment by RahulMohann** [comment]
<img width="649" alt="Download-clientlib-invoked" src="https://github.com/adobe/asset-share-commons/assets/99810531/3604d3bf-dd54-4228-a647-32ef7cc035b8">

**Comment by davidjgonzalez** [comment]
I'll try to find some time tomorrow to look at this!

**Comment by davidjgonzalez** [comment]
Ok - so this was trickier than i thought :)  -- this could need 2 changes depending on your requirements:

1. One for the download button on the card/asset details
     - If you cant use direct downloads, then you'd want to attach a click handler yourself to these buttons via the [data-asset-share-asset-id] attr or something like that, to trigger a specific file download. If you CAN use direct downloads then #2 below addresses htis.
3. Another for the Download modal (which pairs with Cart and License) 
     - This is best done in the ASC project itself. I've attached a `ui.apps` package w/ this functionality for you to test out (on a dev instance) .. to enabled it, you need to goto your Download modal component > Behavior tab and toggle on the new "Avoid zip downloads" .. with this enabled, it will try to download JUST the file when exactly 1 asset and 1 rendition are the target of a download ... This should work w/ direct downloads as well. These single files will NOT queue up in the Downloads modal, rather they will immediately start downloading to your computer. 
 
![2023-11-29 at 6 46 PM](https://github.com/adobe/asset-share-commons/assets/1451868/d8e31a6c-2779-49e6-b9e8-acbe9a3a76b7)
         
[asset-share-commons.ui.apps-3.5.1-SNAPSHOT.zip](https://github.com/adobe/asset-share-commons/files/13506631/asset-share-commons.ui.apps-3.5.1-SNAPSHOT.zip)

Let me know how this snapshot works, and i can cut a release w/ it if it works well.

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez , Can you please let me know how to proceed here?
Thanks for your support.

**Comment by davidjgonzalez** [comment]
@RahulMohann  do you have an RDE You could install the ui.apps package on directly? You could try adding that ui.apps into  a /apps/xxx/vendor-packages/application/install folder -- i think this one should supersede the one from your ASC all package.

1. Download feature in the card (with or without direct download enabled) should download the single file and not zip.
   - This would work "OOTB" w this patch if you set Direct Downloads with a single rendition pre-selected.
   - If you want to allow for download > 1 rendition, then you'd have to customize this.
2. Download feature in the asset detail page should also download the single file and not zip
   - This would work "OOTB" w this patch if you set Direct Downloads with a single rendition pre-selected.
   - If you want to allow for download > 1 rendition, then you'd have to customize this.
4. The cart function should work as is. Means it should download multiple files as zip. 
   - This should work w/ the patch.

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez ,
I've tested this package and it works well as per our expectation. How can we proceed further? Will you be adding this in a new ASC version? If yes, how soon we can expect that version? We are currently in 3.3.0.

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
This is now in ASC v.3.6.0 (just released)
