### ISSUE TITLE
when I try to deploy the project on cloud I get errors

### ISSUE THREAD

**Issue by inheritedburrp** [adobe/asset-share-commons#1036]
aio aem:rde:install all/target/asset-share-commons.all-3.4.3-SNAPSHOT.zip 
Uploading ████████████████████████████████████████ 100% | ETA: 0s | 7730/7730 KB
#9: deploy staged for content-package asset-share-commons.all-3.4.3-SNAPSHOT.zip on author,publish - done by 12341234cc2342cc3c.e at 2023-11-08T14:13:26.743Z
Logs:
> The analyser found the following errors for author and publish : 
> The analyser found the following warnings for author and publish : 
> [configuration-api] Configuration org.apache.sling.commons.log.LogManager.factory.config~asset-share-commons: Property org.apache.sling.commons.log.pattern - Property is not allowed (asset-share-commons:asset-share-commons.all:3.4.3-SNAPSHOT|asset-share-commons:asset-share-commons.ui.config:3.4.3-SNAPSHOT)
> [api-regions-exportsimports] com.adobe.aem.temp:medi-aem-sites.core:1.0.0.SNAPSHOT: Bundle medi-aem-sites.core:1.0.0.SNAPSHOT is importing package(s) Package com.day.cq.wcm.api;version=[1.30,2) in start level 20 but no visible bundle is exporting these for that start level in the required version range.
> [api-regions-exportsimports] com.adobe.aem.temp:assetshare.core.cloud:3.4.2: Bundle assetshare.core.cloud:3.4.2 is importing package(s) Package com.day.cq.dam.commons.util;version=[1.68,2) in start level 20 but no visible bundle is exporting these for that start level in the required version range.
 ›   Error: [RDECLI:INSTALL_STAGED] Install command was staged, analysers detected missing packages that can be fixed with another deployment on top of this one.
 ›    Please check logs. If this is expected, you can ignore exit code 40
 ›   Code: INSTALL_STAGED

**Comment by davidjgonzalez** [comment]
mmm - i able able to install this on my RDE. are you still having this problem? Can you try resetting your RDE and trying again?

**Comment by davidjgonzalez** [comment]
Please re-open if you still have issues.
