### ISSUE TITLE
Search Results when used for full text search is returning assets outside of the configured search paths

### ISSUE THREAD

**Issue by tarkash-88** [adobe/asset-share-commons#1037]
We are observing a major issue with the OOTB search results page. When a full text search is done, the results returned are from folders outside the "search paths" configured in the Search results component. 
I have tested this with vanilla AEM SDK version 2023.9.13665.20230927T063259Z with ASC version 3.4.0 deployed. 
We are observing this issue for our project as well.

CC: @arpithaar @davidjgonzalez

**Comment by tarkash-88** [comment]
This issue is a blocker and would need immediate attention.

**Comment by prachmahajan** [comment]
![image](https://github.com/adobe/asset-share-commons/assets/40654970/7256d7d3-17e5-474c-a19a-11e2ae542799)
We have given project specific path but still assets from CSS folders are shown.

**Comment by davidjgonzalez** [comment]
Working on a fix!

**Comment by davidjgonzalez** [comment]
Fixed in V3.5.0
