### ISSUE TITLE
Do ASC support excel file? 

### ISSUE THREAD

**Issue by Lovekeshgoel** [adobe/asset-share-commons#1086]
Hi,

Do ASC support excel file? Please let me know if yes what changes we have to do for it?

**Comment by davidjgonzalez** [comment]
@Lovekeshgoel Sure - theyre just assets. I expect youd want to make a details page for them since they dont really have a normal "preview" .. 

Not sure if you have anything specific in mind

**Comment by Lovekeshgoel** [comment]
But how can I do that. I am looking for any documentation. It is same. I mean I can use document page under details.

**Comment by davidjgonzalez** [comment]
You would make an Asset Details page under `details` with the value that is returned by whatever Asset Details Selector [1] 
you have configured. If you dont know what this is, you can add a metadata details component on the details page, configure it to display whatever computed property is driving it (ex. Asset Type, or Content Type) and see what that value is. The page name is that value, lowercase with hyphens. 

If needed you can also implement your own Asset Details Selector impl.

https://opensource.adobe.com/asset-share-commons/pages/search/search-page/#asset-details-page-selector

**Comment by davidjgonzalez** [comment]
Also - this probably requires renaming your details pages, but the Content Type asset selector is alittle niceer than the Asset Type (which relies on some OOTB AEM group utils) ... Here's the values (turn to lowercase and hyphen fro spaces) that you can use as details pages ... so an Excel doc would have a details page name of "excel" ... a Word Doc would have "word-doc" .. etc based on these mime/type to content type name rules in the code below.

https://github.com/adobe/asset-share-commons/blob/main/core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/ContentTypeImpl.java#L67-L99
