### ISSUE TITLE
Filter's checkboxes aren't checked correctly, if user opens a link with some filter parameters

### ISSUE THREAD

**Issue by OleksandrBarybin** [adobe/asset-share-commons#1117]
**Describe the bug**
Rendering of selected fields in the filter isn't correct after copy+paste of the url, if there are more than one field with similar resource type configured
**Also reproducible in the sandbox**

**Environment**
* aem.enablementadobe.com
also
* AEM Version: AEMaaCS 2023.12.14538.20231205T165334Z-231100
* Asset Share Commons Version: 3.8.4
* both, also local

**To Reproduce**
1. Open https://aem.enablementadobe.com/content/asset-share-commons/en/light.html
2. Select type == _Image_, and DRM == _Restricted_
3. Search results are updated
4. Copy + paste url to the new tab

**Expected behavior**
Both checkboxes are checked, correct results are shown

**Screenshots**
Only first checkbox is checked, but correct results are shown

**Additional context**
Simple scenario
If I have 2 filters configured, and both are `sling:resourceType="asset-share-commons/components/search/property"`
After doing described steps -> first is always showing correct selected options, second is always empty, so depending on the order, not on the configs of the filters
Probably logic in PredicateUtil#getInitialValues should be adjusted

**Comment by davidjgonzalez** [comment]
This fixes it: https://github.com/adobe/asset-share-commons/pull/1118

**Comment by OleksandrBarybin** [comment]
It works perfectly now, thank you!
