### ISSUE TITLE
Browser Back / Forward Button Click changes the URL, but actual navigation does not happen and Previous or Next page does not get loaded.

### ISSUE THREAD

**Issue by dragandimic** [adobe/asset-share-commons#1119]
**Describe the bug**
Browser Back / Forward Button Click changes the URL, but actual navigation does not happen and Previous or Next page does not get loaded. This seems to be the issue only when filtering assets. When you navigate to details page and then click browser back button (not the back UI button in the details page) - the previous page does get loaded. This is not the case whit filter urls. 

**Environment**
aem.enablementadobe.com
also
AEM Version: AEMaaCS 2023.12.14538.20231205T165334Z-231100
Asset Share Commons Version: 3.8.4
both, also local

**To Reproduce**
1. Go to demo light page for Asset Share ( https://aem.enablementadobe.com/content/asset-share-commons/en/light.html )
2. Click on right side filter `TYPE > VIDEO` (once clicked - results grid will update.
3. Click browser BACK button.
4. URL changes to previous url (home page) but the previous page does not load (the page content remains the same as when `TYPE > VIDEO` filter was applied).
5. the same happens when any other filters are applied.
6. for example - you can click again on the `TYPE>VIDEO` filter and then add another filter `TYPE>IMAGES`.
7. the results grid will be updated with new results.
8. click on the Browser back button once and then once more.
9. url changes once and then once more - but previous pages do not get loaded - the page with 2 filters applied is shown to the user.

**Expected behavior**
Click on the browser button should change url to previous url AND also load the previous page. The url change should also navigate to that particular page / url.

**Screenshots**

https://github.com/adobe/asset-share-commons/assets/129842971/cf03268c-4111-4061-b5e0-0ebe4495ea2f

**Additional context**
nothing to report here

**Comment by davidjgonzalez** [comment]
This should fix it: https://github.com/adobe/asset-share-commons/pull/1120
