### ISSUE TITLE
Checkboxes and texts in the multi-field Options tab in component Path Filters are overlapping

### ISSUE THREAD

**Issue by sarmic30** [adobe/asset-share-commons#1127]
**Describe the bug**
While authoring the multi-field **Option** tab in the component **Path Filters** from component group **Asset Share Commons - Search** the check-boxes and texts in the multi-field are overlapping. This is tested in Vanilla Instance with the latest SDK version and the latest Asset Share Common version [3.8.6] as well.

**Environment**
* AEMAACS Version: 2024.4.15977.20240418T174835Z-240400
* Asset Share Commons Version: 3.4.0
* Author

**To Reproduce**
1. Go to component **Path Filters** from component group **Asset Share Commons - Search**  and drag and drop the component for authoring
2. Click on edit option and edit the component
3.When you open and edit the multi-field option tab in the dialog you will see that the check-boxes and texts are overlapping 

**Expected behavior**
The check-boxes should be properly aligned with the texts.

**Screenshots**

![PathFilter Dialog](https://github.com/adobe/asset-share-commons/assets/169160390/82f253f8-798c-471f-8af6-c48529789cb2)

**Comment by davidjgonzalez** [comment]
@sarmic30  did you figure this out? This is all GraniteUI so im not sure if its a bug with GraniteUI itself, or if there is a better way to construct the dialog to make it so they don't overlap.
