### ISSUE TITLE
.mov Quicktime files are not playing in video player

### ISSUE THREAD

**Issue by intaglioman** [adobe/asset-share-commons#1131]
**Description**
We came across this, not sure if its fully widespread or not, we noticed that none of our client's .mov files are playing in the details page video player. We confirmed that the videos do play successfully in author dam. Anyone else come across this?

**Environment**
* AEM Version: AEMaaCS
* Asset Share Commons Version: 3.8.4
* It can be seen on publish and author view as published
* We might have narrowed it down to working on Safari only.

**Expected behavior**
.mov file should play from browser preview when on the details.html page

**Comment by davidjgonzalez** [comment]
What rendition of the MOV asset are you trying to play in the Details page? How is that configued?

**Comment by intaglioman** [comment]
We didn't setup any renditions, so would have been just the ootb from the processing profile, but I believe we found a workaround.... Also, this project has ended and I can no longer replicate the issue :\

**Comment by davidjgonzalez** [comment]
If you only have MOV, then youre likely running into a browser limitation -- and ASC can't do anything about that.  For example here's the same MOV in a video tag in Chrome (No video, just audio) and Safari (Audio and video). This is a test HTML file so as nothing to do w/ ASC or AEM at all, showing how browser's support different files.

It seems like the consensus online is if you want corss-browser support,  the best thing to do is generate MP4 renditions of the MOV and play that. Feel free to google around "playing MOV videos in browser X"


![2024-07-19 at 10 41 AM](https://github.com/user-attachments/assets/35a697e0-5273-4222-8dd3-6fde8f35d70c)
