### ISSUE TITLE
Navigation Menu is appearing for all the renditions including the desktop view

### ISSUE THREAD

**Issue by sarmic30** [adobe/asset-share-commons#1169]
The **Menu** option in the Top Navigation bar  along with Top Navigation Items are appearing on the landing page of Asset Share Common  which is visible for all the screen resolution including the desktop view. Earlier the Menu used to appear only for certain screen resolutions and the whole navigation menu used to be hidden when the **Menu** option was available.
Is this the expected behavior now?It does not make sense to display the top Navigation twice in the **Menu** option as well as in the Top Navigation Tab for all the available screen resolutions.

* AEM Version: **AEM as Cloud Service**
* Asset Share Commons Version:**3.8.10**
* Both Author and Publish 
* SDK version: **2024.6.16971.20240628T122619Z-240600**

1. Go to Asset Share Common landing page
2. Click on **Menu**  from the Top Navigation bar

**Expected behavior**
The **Menu** option should be visible only across certain Screen Resolutions. And when the Menu option is visible the Top Navigation Items should not be visible.

**Screenshots**
![image](https://github.com/user-attachments/assets/58fda3f8-c348-4d26-b482-e00f8c80778d)
![image](https://github.com/user-attachments/assets/0c96440a-8742-4e05-b156-7f6f8bfd3e84)
![image](https://github.com/user-attachments/assets/becb72d9-ebf1-4c19-b82a-54dbe9e42568)

Please confirm if this is the expected behavior or a bug that is needed to be fixed?

**Comment by davidjgonzalez** [comment]
This is a bug. Fix coming soon.
