### ISSUE TITLE
JSON option in Property Filter component is throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by sagaciousagi** [adobe/asset-share-commons#1171]
**Describe the bug**
JSON option in Property Filter component is throwing UnsupportedOperationException

**Environment**
* AEM Version: AEM as Cloud Service 
* Asset Share Commons Version: 3.8.12
* Author, Publish or both? Both

**To Reproduce**
1. Go to Asset Share Commons landing page
2. Add a Property Filter Component in the filter section and open dialog. 
3. Choose "Dropdown" in Type field and select the Source as "JSON" and provide the JSON from AEM repo. e.g. /content/dam/testData.json
4. Page will crash. 

**Expected behavior**
Page should not crash. Property Filter should render the dropdown content on page. 

**Screenshots**
<img width="642" alt="image" src="https://github.com/user-attachments/assets/9ce5c8b5-7c6a-4904-8449-8635e3fa0e3d">

**Comment by sagaciousagi** [comment]
PR raised: https://github.com/adobe/asset-share-commons/pull/1172

**Comment by davidjgonzalez** [comment]
Fixed in 3.18.14
