### ISSUE TITLE
PDF Viewer not loading on page refresh

### ISSUE THREAD

**Issue by RahulMohann** [adobe/asset-share-commons#1180]
**Describe the bug**
We are using the PDF viewer component in our detail page to render pdf and other documents. We are observing the below behavior.

1) Login to the ASC and then open a pdf from the search page. It (detail page) loads for the first time and PDF is getting rendered in the pdf viewer component.
2) Refresh the same detail page once and the PDF viewer doesn't load.
3) Go back to search page and open another PDF, still the pdf viewer doesn't load.
4) Clear the browser cache and do refresh the detail page and the PDF viewer loads and render the document.

Any idea why this is happening and how to fix?

**Environment**
* AEM Version: 2024.8.17465.20240813T175259Z
* Asset Share Commons Version: 3.8.12
* Author, Publish or both: Publish

Thanks,
Rahul

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez , Could you please check?

**Comment by davidjgonzalez** [comment]
@RahulMohann im away until October.

Can you check to see if there are JS errors? Do you see the PDF download HTTP request taking place and completing in the Network panel?

I assume this is a problem with the PDF JS SDK since that is all clientside; all ASC does is popular the HTML/script tag w/ the configured values.

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez, I see the document download request always happens successfully. But there is an iframe that doesn't get loaded when you refresh. Attached is the screenshot. If it's a client-side issue, how can we fix it?

Thanks,
Rahul
