### ISSUE TITLE
Issue installing on Local Jar with Service Pack 6.5.21

### ISSUE THREAD

**Issue by tysonbowman** [adobe/asset-share-commons#1196]
**Question?**
* What piece of functionality do you have a question about?
Asset Share Common Bundle not resolving
com.adobe.cq.wcm.core.components.models.form,version=[14.3,15) -- Cannot be resolved

* What are you trying to achieve?
Trying to install it an unable to resolve the jar.

Created a new server and installed 6.5.21 without issue and when installing asset share commons 16, 18 and 20.  Each have the same issue.

Documentation can be found here: https://opensource.adobe.com/asset-share-commons/. It might answer your question!

**Comment by davidjgonzalez** [comment]
This means you dont have AEM WCM Core Components installed (or atleast not a version that ASC requires).

Install Core Components and it should work.
