### ISSUE TITLE
How to revive legacy "flatStructure" download

### ISSUE THREAD

**Issue by zhgeric** [adobe/asset-share-commons#1197]
**Question?**
* What piece of functionality do you have a question about?
About the asset download functionality
* What are you trying to achieve?
What should I do to prevents the creation of additional folder that wraps my assets in my zip file while downloading ?
Like in the legacy mode "flatStructure"

**Comment by davidjgonzalez** [comment]
I think we'll have to add a toggle  to the dialog that lets you force a flat structure and check that on like 118 here:

https://github.com/adobe/asset-share-commons/blob/develop/core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/AsyncAssetRenditionsDownloadServlet.java


I'm not sure what would happen if you have 2 assets w the same file name tho (but in different assets folders)

**Comment by zhgeric** [comment]
I don't really understand what to do here.

Do I need to force 118 to false ?

I tried doing that but the folder is still created

**Comment by zhgeric** [comment]
Seems like my Post request is going to https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsDownloadServlet.java and not the async one

**Comment by davidjgonzalez** [comment]
Are on on SDK? SDK doesn't have the AEM async download framework. 

You'd have to develop against an RDE to dev/test against the async stuff

**Comment by zhgeric** [comment]
I may have succeded somehow, but that doesn't seem a clean way to do it.

https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsDownloadServlet.java

https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsZipperImpl.java

I took these both into my code and set it to false and that did the job mmh

**Comment by davidjgonzalez** [comment]
Ahh - yes, if you're going to run this on AEM as a cloud service you need to do it in the async. If your are running 6.5 the you'd do it on the old one.

**Comment by zhgeric** [comment]
By the way, I was wondering "I'm not sure what would happen if you have 2 assets w the same file name tho (but in different assets folders)" what is happening right now when 2 assets w the same name is being downloaded ? The 2nd asset isn't downloaded ?
`if (folderName != null && !zipEntryFolderNames.contains(folderName)) {
                            addFolderAsZipEntry(folderName + "/", zipOutputStream);
                            zipEntryFolderNames.add(folderName);
                        }`

**Comment by davidjgonzalez** [comment]
Thinking about adding this into the main-line -- do you need this for AEM CS or 6.5?

**Comment by zhgeric** [comment]
I'm using 6.5
