### ISSUE TITLE
Define and apply BEM Class APIs to components

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/asset-share-commons#166]
We should go through, define and apply BEM CSS Classes to all components exposing a public API for all components in ASC (and document this API).

We should also move the wrapping class out of the cq:htmlTag node definition, into the component itself.

This would well position us for enabling the Style System on the components.

**Comment by godanny86** [comment]
👍 💯

**Comment by davidjgonzalez** [comment]
Should be fixed now
