### ISSUE TITLE
Initial cloning takes long and consumes a lot of disk space

### ISSUE THREAD

**Issue by joerghoh** [adobe/asset-share-commons#21]
The cloning downloads around 230 megabytes, and then takes 460 MB on disk.

```
$ git clone https://github.com/Adobe-Marketing-Cloud/asset-share-commons.git
Cloning into 'asset-share-commons'...
remote: Counting objects: 2392, done.
remote: Compressing objects: 100% (1333/1333), done.
remote: Total 2392 (delta 677), reused 2385 (delta 670), pack-reused 0
Receiving objects: 100% (2392/2392), 231.59 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (677/677), done.
$
```

In the `ui.content` module there are a number of assets and media elements (mp4 files), which are quite large. Is it necessary to have them in this git repo?

**Comment by davidjgonzalez** [comment]
@joerghoh agree; its convenient having ui.content  in one repo is why we did this, however i think the mp4 files could be replaced with much smaller variants (even 1 frame videos). 

While it wont make a significant impact, i noticed running image assets through tinypng (and it's ilk reduced filesize by ~10x). Generally agree the size on disk from ui.content is unnecessarily large.

@godanny86 WDYT?

**Comment by godanny86** [comment]
@joerghoh agree as well. I'm actually wondering if we take all of the /content/dam (minus some of the placeholder images) in ui.content and make it a stand alone package. Its primary use case is for demoing IMO...

**Comment by joerghoh** [comment]
As a very first step the demo content should get separated from the application itself, so one can use it without the demo content (btw what's the license of these assets?).

But then it would be benefical if we could get rid of them from this git repository as well.

**Comment by davidjgonzalez** [comment]
@joerghoh it is separated by buld profiles already.

why can’t someone use it without the sample content? I’d argue the only ppl cloning the project (or Developing against it)  SHOULD be using the sample content to validate any changes.

UI.content is NOT part of the distributed artifact. 

As a developer I really like having UI.confent immediately available.

**Comment by davidjgonzalez** [comment]
Also the content is from unsplash.com and freely licensed (@godanny86 can confirm) or thtings we made and are unlicensed.
