### ISSUE TITLE
Possible to add a search filter that allows tag selection?

### ISSUE THREAD

**Issue by ar80001-BRONGA** [adobe/asset-share-commons#266]
One of the teams planning to deploy an asset share has an asset metadata attribute that allows the person searching to select one or more tags, and here's how it's represented as a search filter within the AEM author instance:

![image](https://user-images.githubusercontent.com/33265694/45188110-f6254700-b1e7-11e8-890f-28ef9c577b1c.png)

Would it be possible to add a new Asset Share Commons search filter component to support this use case, provided something does not already exist (I confirmed the available search filters and none of them appeared to handle this use case)?

**Comment by davidjgonzalez** [comment]
@artdirk there is a Tags Filter component [1] but its checkbox/radio based. 
Is the intent here to point it at one or more tag namespaces and allow any number of tags to be selected?

Unfortunately we cant use CoralUI outside of the AEM Authoring experience, so we'd have to find a SemanticUI widget [2] that would easily satisfy this; thoughts on a SemanticUI widget that would work?

[1] https://adobe-marketing-cloud.github.io/asset-share-commons/pages/search/tags/ 
[2] https://semantic-ui.com/modules/dropdown.html

**Comment by artdirk** [comment]
@davidjgonzalez, the use case for the "Marketing Campaign" filter would be to point it at an attribute in our metadata schema (./jcr:content/metadata/gps:marketingcampaign), and allow the asset share user to select one or more values from the list of existing values to filter search results.

**Comment by artdirk** [comment]
@davidjgonzalez, I think the current "hand picked" tags component will not work, because there are a bunch of tags that would need to be manually curated.

I think the idea of a multi-select dropdown that points at a metadata attribute (a "derived" tags component) and exposes all its possible values would be more appealing to the business.
