### ISSUE TITLE
Incorporate ui.tests project

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/asset-share-commons#315]
We should incorporate the WIP ui.tests project even if its only for release-time smoke testing. Current concerns / considerations:

* Test execution is not incorporated into Maven poms
  * I'm not sure how important this is since we don't have the infrastructure to automate this (deploy/test)
* Created a /content/asset-share-commons/test and /content/dam/asset-share-commons/test structures in the ui.content project since using the sample content was far too complex and lacked clarity/controls.
* Initial deployment + run of ui.tests of ASC cause ui.tests to fail since there is a long (seconds) wait time for the client libs to build.

Current state with tests is at: https://github.com/davidjgonzalez/asset-share-commons/tree/feature/ui.tests

**Comment by ireasor** [comment]
I'm in favor of breaking out the test content into a separate content project.  The main reason for this is that while a developer who is working on changes to ASC would want to build and deploy all of the content, a consumer of the project, such as a customer or an SC who is demonstrating it, will likely not want the test content.

**Comment by davidjgonzalez** [comment]
yeh - i agree. was hoping against hope you might have a good reason for me to avoid the extra work :P
