### ISSUE TITLE
Missing artifact com.adobe.aem.commons:assetshare.ui.apps:jar

### ISSUE THREAD

**Issue by jbaix** [adobe/asset-share-commons#348]
Hi masters.

I'm trying to set up my project as described in [1]. I've created a new project with AEM plugin for Eclipse and aem-project-archetype 15.

When I include the Asset Share Commons dependencies, I get an error in the ui.apps pom.xml validation:
"Missing artifact com.adobe.aem.commons:assetshare.ui.apps:jar:1._x.x_"

I've tried with versions 1.0.0 (like in the documentation) and also 1.6.8 and 1.6.10.

I understand this dependency is not required in the ui.apps project, as it is the zip package to be installed in AEM with the project package, which is included as a subpackage. Is it correct?

[1] https://adobe-marketing-cloud.github.io/asset-share-commons/pages/development/guide/

**Comment by jbaix** [comment]
I think there is a mistake in the documentation. The dependency should be included like this in the ui.apps project:

```
	 	<dependency>
			<groupId>com.adobe.aem.commons</groupId>
			<artifactId>assetshare.ui.apps</artifactId>
	  		<type>content-package</type> <!--  Include this line -->
	  		<!--  <version>1.0.0</version> Do not include this line -->
		</dependency>
```
What do you think?
This question can be closed.

**Comment by davidjgonzalez** [comment]
@jbaix the dependencies with version/type/scope should be set in Your reactor POM, and then In your content projects Pom, you can use the dependency like you outline above.

It looks like the docs could be updated tho-  so I’ll leave this issue open to track that.

Thanks for the update!
