### ISSUE TITLE
Exclude Expired assets from landing page

### ISSUE THREAD

**Issue by Lovepreet1994** [adobe/asset-share-commons#439]
Hi,

we have one requirement where we need to restrict expired assets from landing page and expired assets should only be visible with other assets when we search them through property filter.
To achieve this, I have excluded expired assets from home page but now when I try to search expired assets through the filter then am getting only 2 expired assets in the result. Ideally, all expired assets should display.

Regards,
Lovepreet

**Comment by davidjgonzalez** [comment]
Hi @Lovepreet1994  - how exactly are you "excluded expired assets from home page".

After reading this post, it occurred to me that the "Active" selection for the filters doesn't work; If you set filter options to "Active", on page load, they show as selected but since the search form hasn't been submitted yet, they don't take effect until a subsequent search via the UI.

**Comment by Lovepreet1994** [comment]
Hi David,

Through search restrictions i have excluded expired assets.
my requirement is that expired assets should not be visible on home page but they should be searchable through property filter.
Is this possible?

Regards,
Lovepreet

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidjgonzalez** [comment]
@Lovepreet1994 did you log the same issue twice? #439 and #440 using 2 different user names? Are these duplicates? If so can you close so we can focus on 1 issue? If not, can you update each one to clearly state how theyre different? (they seem the same to me)

**Comment by davidjgonzalez** [comment]
For posterity .. this was added some time ago, and can be set via the Search Results component: 

![2023-12-12 at 12 16 PM](https://github.com/adobe/asset-share-commons/assets/1451868/0211915d-0d85-48e6-9c38-b5793f5502db)
