### ISSUE TITLE
Larger size video files are not playing smoothly in Asset share Details page

### ISSUE THREAD

**Issue by assetshare2018** [adobe/asset-share-commons#463]
**Describe the bug**
When we are playing large size video files in details page for example 50MB, 100MB & more than that, it’s not playing smoothly in details page. Please let us know Is there any limitations and recommendation for best video playback experience in details page.

**Environment**
* AEM Version: ? AEM 6.3.3.1 & AEM 6.5.1
* Asset Share Commons Version: ? 1.5.2 & 1.8.0
* Author, Publish or both? Publish

**To Reproduce**
1. Upload large size videos in DAM and publish it (50MB, 100MB and above)
2. Go and check the playback of the video in publisher details page.

**Expected behavior**
Video should play smoothly in details page.

**Screenshots**
NA

**Additional context**
NA

**Comment by davidjgonzalez** [comment]
Do these videos play smoothly from AEM Publish in general? For example, copy the Video URL and past it in a new browser tab, and open it in the browser's native player .. does it play smoothly?
Does this issue occur locally or only on hosted environments?

Im trying to ascertain if the issue is with ASC or with AEM's ability to stream out these video files in a performant manner.

**Comment by assetshare2018** [comment]
Hi David,
Apologies for delay in response and appreciate your response!
We are facing this issue in hosted environments (pre prod & prod). And I could see same playback issue in Publish DAM.

**Comment by davidjgonzalez** [comment]
@assetshare2018 if there is an issue playing back directly from the Asset URL provided by AEM, then it sounds like the issue is with AEM itself. Have you logged a Support ticket?

**Comment by assetshare2018** [comment]
Hi David,
Yes we created the daycare ticket also for this issue, in general any framework mechanism or video player plugin will help to resolve this issue?
