### ISSUE TITLE
Applied Filter is removed when Load more option is selected.

### ISSUE THREAD

**Issue by assetshare2018** [adobe/asset-share-commons#466]
**Describe the bug**
Applied Filter is removed when Load more option is selected.

**Environment**
* AEM Version: 6.5
* Asset Share Commons Version: 1.8.0
* Author, Publish or both? Both

**To Reproduce**
1. Go to Asset share commons home page in author. (/content/asset-share-commons/en/light.html)
2. In right side, edit the property filter component.
3. In Search behavior tab, uncheck the auto search on change option and in Update on Search dropdown list select replace option.
2. Select any filter in type filter section.
3. Scroll down to load more option and click load more.
4. See the filters selected are removed.

**Expected behavior**
When we click the load more option, the selected filter shouldn't be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43200674/70501379-e8c1df80-1b43-11ea-93ba-d831d9909e89.png)
![image](https://user-images.githubusercontent.com/43200674/70501470-24f54000-1b44-11ea-9f94-428ad1f224ac.png)
![image](https://user-images.githubusercontent.com/43200674/70501517-40604b00-1b44-11ea-8b08-b06afa23eb0f.png)
![image](https://user-images.githubusercontent.com/43200674/70501570-684fae80-1b44-11ea-8575-a0f00dc870cc.png)

**Comment by rajat1020** [comment]
@davidjgonzalez Can you please share some light on this issue? Its pending from long time.

**Comment by davidjgonzalez** [comment]
@assetshare2018 I cant reproduce on the latest. See the attached video. 

[asc-issue.rename-to-mp4.txt](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4059622/asc-issue.rename-to-mp4.txt)

**Comment by assetshare2018** [comment]
@davidjgonzalez Could you please uncheck Auto-Search on Change option to reproduce this issue.
