### ISSUE TITLE
How do we add thumbnail in audio file?

### ISSUE THREAD

**Issue by khanaaqib** [adobe/asset-share-commons#526]
**Question?**
* What piece of functionality do you have a question about?
* What are you trying to achieve?

Documentation can be found here: https://adobe-marketing-cloud.github.io/asset-share-commons/. It might answer your question!

**Comment by khanaaqib** [comment]
I have developed  audio component in Asset share commons.Everything is working fine except that I am not able to add thumbnails in audio file.Any help will bee appreciated. PFB detail.
![image](https://user-images.githubusercontent.com/35225284/82565695-7a745500-9b98-11ea-9447-2cac7edfbab8.png)

**Comment by khanaaqib** [comment]
When I have uploaded  audio file in dam  only the original rendition has appear in renditions folder.Inside home page audio folder has appears without any thumbnail.

**Comment by godanny86** [comment]
Hi @khanaaqib i think ootb AEM Assets does not create image renditions for audio files. You might have to upload your own or extend the DAM Update Asset workflow in some way. Another alternative is to use the **Missing Image** parameter for the Search Results component https://adobe-marketing-cloud.github.io/asset-share-commons/pages/search/results/

**Comment by khanaaqib** [comment]
Hi @godanny86 I have tried missing image parameter thing,when I have applied  this it is reflected in other component as well  like image and video etc.PFB details.
<a class="image cmp-image__wrapper--card" href="${assetDetails.fullUrl}">


              <img src="${asset.properties['rendition?name=card'] && properties['missingImage'] @ context = 'attribute'}"
                 class="cmp-image--card"
                 alt="${asset.properties['title']}"/>

        </a>
when i was modified that code the missing image reflected all over the component but my requirement is that it is reflected only audio component.

![image](https://user-images.githubusercontent.com/35225284/82662814-2a56ca80-9c4c-11ea-96ed-26325c47bbae.png)


I have done some other changes as well but still not get the result.Can you please suggest the steps where can I change the code to get desired output.

**Comment by khanaaqib** [comment]
Can anyone please help me in this.I have tried several things but I have not got the success.

**Comment by davidjgonzalez** [comment]
@khanaaqib as danny mentioned, AEM does not create image thumbnails for audio files.
I think the best thing for you to do is to create a WF step that adds whatever thumbnails you want to your audio assets. I assume these would be copying some "static audio thumbnail images" to each of the audio assets. If you do this, and you match the rest of the thumbnail naming structure the "rest of AEM" should be able to leverage these thumbnails as welll, and ASC should "just work" too!
