### ISSUE TITLE
PDF Viewer Component for PDF Asset 

### ISSUE THREAD

**Issue by vineelakarnati** [adobe/asset-share-commons#536]
**Is your feature request related to a problem? Please describe.**
When we open a PDF Asset it shows just the first page, only on download user can have a look at all the pages. But with this feature without downloading we can have a View of all pages along with scroll bar, Annotate the text , Search for a text. It has 3 variations Full Window, Sized Container, In Line. With the use of this component user's saves lot of time and resources  as downloading of pdf is not needed.

**Describe the solution you'd like**
For this PDF Viewer component we can leverage PDF Viewer Core Component and make MimeType Changes so PDF asset would open in "/content/asset-share-commons/en/light/details/pdf.html" instead of "/content/asset-share-commons/en/light/details/document.html" page. For Rendering this component user can have Document Cloud View SDK Integration . This would need implementation of Context Aware Configuration / OSGI Configuration / Combined approach of both configurations

**Describe alternatives you've considered**
On absense of this integration user can download the asset using Download action button. A Message is shown in this component to configure Document Cloud View SDK Integration ID

**Additional context**
                                                        **Full Window Variation**
![image](https://user-images.githubusercontent.com/18096665/90108311-bc600200-dd67-11ea-8bff-01395b0a33b4.png)
                                                            **In Line Variation**
![image](https://user-images.githubusercontent.com/18096665/90108376-d4378600-dd67-11ea-9cbb-26dcb54012c4.png)

**Comment by vineelakarnati** [comment]
Hi David and Daniel
@davidjgonzalez @godanny86 could you please share your thoughts on this Feature Request.

**Comment by anoopbhatn** [comment]
@vineelakarnati @davidjgonzalez  @godanny86 
Any updates on the above ? Was this implemented by any chance ?

@vineelakarnati , if not, what did you end up doing for your use-case that needed this implementation.

**Comment by RahulMohann** [comment]
Any hope on this?

**Comment by Robedean** [comment]
@davidjgonzalez wanted to see if there has been anythign on this. I think this reader would hold a lot of value as a feature, not just for PDF's but for PowerPoints as well. Do you know of anything that already exists, or would this feature need to be designed from Scratch.

**Comment by davidjgonzalez** [comment]
@Robedean - i have an old branch with this - let me see if i can find it and PR it in.

**Comment by davidjgonzalez** [comment]
Hows this look?

https://github.com/adobe/asset-share-commons/pull/1060

**Comment by davidjgonzalez** [comment]
This has been released in 3.7.0
