### ISSUE TITLE
Asset Share Not working when we have a context path

### ISSUE THREAD

**Issue by aemuser** [adobe/asset-share-commons#540]
**Describe the bug**
Hi, we have an aem instance wherein there is a custom context path defined - "Apache Felix Jetty Based Http Service" 

**Environment**
* AEM Version: 6.5.5
* Asset Share Commons Version: 1.9.4
* Author, Publish or both : Both 

**To Reproduce**
1. Go to Apache Felix Jetty Based Http Service in configMgr, add a custom context path, could be any meaningful context path
2. Click on Save.
4. See error  - Any page on edit mode kind of loads "two" edit bars at the top, breaks the whole environment. 

**Expected behavior**
Expected normal behavior

**Screenshots**

**Additional context**
Do we have to consider any configurations when workign with a context path for the Asset Share to Work ?

**Comment by davidjgonzalez** [comment]
Unfortunately, the lift to make this work is likely very large and not something we'll be able to realistically tackle. :(
