### ISSUE TITLE
Downloading Renditions does not set the File names. 

### ISSUE THREAD

**Issue by sasikala-rajkumar** [adobe/asset-share-commons#561]
Asset Share commons version - 1.8.0
Environment - AEMaaCS
Asset Share Component - Renditions.
Current Behavior - Downloading Asset Renditions does not include the name of the File. The downloaded file names are original, different rendition names. ( Files with extensions pdf, jpg, etc )
![image](https://user-images.githubusercontent.com/52685735/104140781-1ef21400-5381-11eb-96fd-e1a9d6235b9a.png)

Actual Behavior - Downloaded Files should have its actual file names with extensions. 
It works fine in the Local SDK instance but the issue exists in the Cloud instances.

**Comment by davidjgonzalez** [comment]
![image](https://user-images.githubusercontent.com/1451868/108415040-f4566f00-71fa-11eb-8f1c-8f039060c799.png)

Have you been able to try with 1.9.4? Above is a screenshot of my experience w/ 1.9.4 using Chrome.

**Comment by davidjgonzalez** [comment]
Please re-open if you are still experiencing this issue.
