### ISSUE TITLE
Support more than 1 Search Result components on the same page

### ISSUE THREAD

**Issue by briceooOO** [adobe/asset-share-commons#562]
When adding multiple search result components to the same page, the configuration of the first one is applied to the next ones (layout config, assets path and so on).
Would be really cool to be able to create rich pages with multiple lists of assets to introducea bunch of assets, type by type, usage by usage, mixing content and assets from the DAM as per author needs.
![Search-Result](https://user-images.githubusercontent.com/16735591/104608724-84e0e300-5682-11eb-8b00-88e535d3d631.jpg)

**Comment by briceooOO** [comment]
Thanks for the answer. 
The filter component could be applied to all the Search Results and each Search Result component could point to different root folders without interferences.
Each Search Result compoment config should be kept independant not to have unexpected behaviour.

**Comment by davidjgonzalez** [comment]
yeah - that's a solution - it might get tricky for authors to grok the mapping/relationship between components -- understanding there are always solutions, it's about a tenable solution (from developing/testing, to maintaining, to using :) ) 

Have you looked at that Core Components List component? [1] w/ a search and maybe a customer item overlay? I dont recall if List component prevents you from listing Assets, but if it doesn't, you could make a custom item.html and use the Asset Model on the included resource to re-create the cards.

[1] https://experienceleague.adobe.com/docs/experience-manager-core-components/using/components/list.html?lang=en#design-dialog

**Comment by briceooOO** [comment]
Ok got it. Thanks for the recommandation and resources.
Do you want me toclose the ticket, or you want to keep it open to come back on this potiential feature extension later ?

**Comment by davidjgonzalez** [comment]
@briceooOO lets leave it open - its an interesting idea (we started to build it out this way - that's why there is a `getFormId()` concept -- it just got too complicated to extend this pattern out across everything it needed to touch, and we didnt have a good overall UX approach for indicating the authors/users what filters would impact which results.  Maybe in later versions as we evolve it, this could become easier to achieve.

**Comment by briceooOO** [comment]
Perfect, thanks!

**Comment by davidjgonzalez** [comment]
Ok, closing this for now for tidiness - but keeping enhancement tag.
