### ISSUE TITLE
Analytics on  Download/Share/Add to Cart

### ISSUE THREAD

**Issue by shijuc18** [adobe/asset-share-commons#567]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We have a requirement to get analytics on how many downloads / add to cart / share are happening for an image or a set of images. We are using the 1.8.0 version of Asset Share Common as is without any custom changes. Is it possible to add the feature of above tracking without integrating ASC code with our application code. If there is already a system available to achieve this, can you please share the information ? 

**Describe alternatives you've considered**

Integrate the ASC 1.8.0 source code with our application code and modify action buttons html to trigger to a servlet when buttons are clicked and log the events and splunk it. 

**Additional context**
Not applicable

**Comment by shijuc18** [comment]
Hi All - We integrated ASC 1.8.0 with our code. Able to identify the triggering point for initial down load link on the page at download.js. But on the popup, where on click of download,  actual download happens, we are not able to get control of that click in the code. Any guidance would be appreciated.

**Comment by davidjgonzalez** [comment]
Don't you just need to bind an `onclick` selector to the buttons of the modal? Where exactly are you getting stuck?
