### ISSUE TITLE
Scroll Buttons are not appearing for POP UP in asset share commons 

### ISSUE THREAD

**Issue by ashismit** [adobe/asset-share-commons#568]
We have implemented asset share commons in the project. Issue is when a list of assets is added to a pop up the size of the pop up increases more then the screen and there is no scroll bar to see the whole POP UP.

Steps  to reproduce.

1. Go to the asset share commons serach page .
2. Add 10 to 15 assets in the basket.
3. Open the basket.
4. You will notice the issue with the basket pop up.

*Environment*
* AEM Version: 6.5.6
* Asset Share Commons Version: 1.9.4
* Author, Publish- both

*Screenshot*
![BasketScreen](https://user-images.githubusercontent.com/38585073/108680168-891ade80-7513-11eb-82d2-546392a04498.PNG)

**Comment by davidjgonzalez** [comment]
Does this have the same symptoms on a un-modified ASC installation? It looks like you've provided some custom CSS.

Also, what browser are you using?

**Comment by ashismit** [comment]
@davidjgonzalez the browser tested is firefox and mozilla.

**Comment by ashismit** [comment]
@davidjgonzalez  also seeing the same on the un-modified ASC installation

![Capture](https://user-images.githubusercontent.com/38585073/108867308-13019f00-761b-11eb-991a-80f418bde614.PNG)

**Comment by davidjgonzalez** [comment]
agh - yes, this was an issue with the height of the modal. 

This is fixed in Asset Share Commons 2+ but if you want to drop your own CSS override put in something like this (which is the fix):

https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/less/modals.less

**Comment by davidjgonzalez** [comment]
please re-open if the fix doesnt work for 1.x and/or if you cannot upgrade to 2.x (which is technicall a "breaking change" version - checkout: https://opensource.adobe.com/asset-share-commons/pages/getting-started/upgrade/ )
