### ISSUE TITLE
Should Component Interfaces be annotated as @ProviderType

### ISSUE THREAD

**Issue by shsteimer** [adobe/asset-share-commons#604]
**Question?**

This is very much related to #522. We are extending the EditorLinks component `public class EditorLinksImpl implements EditorLinks` and cloud manager flags this as a Critical Problem:

```
The product interface com.adobe.aem.commons.assetshare.components.details.EditorLinks annotated with @ProviderType should not be implemented by custom code.
```

I guess my question is, does it make sense for all the component interfaces to be annotated as such? Or would the core components model, where the interfaces are Consumer Types with a default internal implementation, make more sense to allow for extension where needed by implementers?

**Comment by davidjgonzalez** [comment]
@shsteimer I don't recall off the top of my head, how do you tell Sling to prefer one Model impl over another? (since they're referenced by interface).

I guess, if you did this, you would only have to deploy a custom impl, and keep the ASC provides cq:Component impl? We could do change this.

**Comment by shsteimer** [comment]
> how do you tell Sling to prefer one Model impl over another
By resource type https://sling.apache.org/documentation/bundles/models.html#associating-a-model-class-with-a-resource-type-since-130-1

**Comment by davidjgonzalez** [comment]
ok, maybe im thinking about this for a different usecase.. 

1. ASC provides EditorLinksImpl implements EditorLinks and bound to RT: asc/components/editor-links
2. Custom provides MyEditorLinksImpl implements EditorLinks and bound to RT: asc/component/editor-links

Author drags the ASC Editor Links component (with RT: asc/componens/editor-links) onto the page ... which Model Impl is selected? 

I guess the other approach would be:

1. ASC provides EditorLinksImpl implements EditorLinks and bound to RT: asc/components/editor-links
2. Custom provides MyEditorLinksImpl implements EditorLinks and bound to RT: custom/component/editor-links
3. Custom EditorLinks cq:Component is defined with RT: custom/component/editor-links and  superRT: asc/components/editor-links

Author drags the Custom Editor Links component (with RT: custom/componens/editor-links) onto the page and the custom MyEditorLinksImpl is selected.

Youre thinking the latter approach? Or something else?

**Comment by shsteimer** [comment]
Yea, exactly, the latter approach. There isn't a way that I know of to make the first approach work, asc/components/editor-links will always select EditorLinksImpl (or at minimum, which model it selects is indeterminate).

**Comment by davidjgonzalez** [comment]
@shsteimer gotcha - yeh, that would work. 

@justinedelson there isn't a way to force rank a Sling Model Impl for a resource type that we're missing, is there?

**Comment by justinedelson** [comment]
@davidjgonzalez I'm assuming that the context here is when doing `adaptable.adaptTo(EditorLinks.class)`. In this case, the configured `ImplementationPicker` services are used. By default there are two such services -- one (https://github.com/apache/sling-org-apache-sling-models-impl/blob/master/src/main/java/org/apache/sling/models/impl/ResourceTypeBasedResourcePicker.java) which looks at resource types and one (https://github.com/apache/sling-org-apache-sling-models-impl/blob/master/src/main/java/org/apache/sling/models/impl/FirstImplementationPicker.java) which just returns the first one alphabetically. 

In the specific use case here, I think there are two options for ASC: (1) do nothing and leave it up to the downstream to implement the `ImplementationPicker` SPI or (2) implement the SPI and do something where a custom implementation is always preferred to the "standard" implementation. The problem with #2 IMO is that it might _still_ be indeterminate which one is picked if there were multiple custom implementations.

**Comment by davidjgonzalez** [comment]
@justinedelson oohh!!  I think the majority use-case is getting models in HTL; there COULD be (unlikely) corner cases where modalFactory is used. 

I'm trying to imagine when you'd want 2 custom impl's... having a hard time unless it's a tenanted asset share. We could always add some (OSGi config-based?) mapping (ex. path to java package) later if needed.

@shsteimer WDYT? Is there value in just providing a custom Impl and using the ASC-provided cq:Component? I suppose this would make it hard to delegate to the OOTB impl though (not sure how it could ever get picked). Does the ability to delegate outweigh the annoyance of creating your own cq:Component?

**Comment by shsteimer** [comment]
@davidjgonzalez yes, absolutely delegation is key. Personally, I think it's somewhat dangerous to modify the behavior of an existing component via a custom model without creating your own cq:Component. I'm really looking for 2 things

1. ability to create a custom cq:Component without requiring a custom HTL script
2. ability to create custom model which deleteagates some functionality to the ASC-provided model, but overrides others.

**Comment by davidjgonzalez** [comment]
Ok! simple enough! Im fine w @ConsumerType!

**Comment by justinedelson** [comment]
> @justinedelson oohh!! I think the majority use-case is getting models in HTL; there COULD be (unlikely) corner cases where modalFactory is used.

To be clear @davidjgonzalez , the distinction I was trying to make was between using Java/HTL (where the ImplementationPicker is used) and the Exporter framework. I don't remember offhand how it works in the Exporter framework and would have to dig further to doublecheck.

**Comment by davidjgonzalez** [comment]
@justinedelson no worries/bother checking - sounds like it wont be needed anyhow -- @shsteimer  actually wants discrete RT's anyhow. 

Thanks for dropping the tip on the Picker! TIL!
