### ISSUE TITLE
Problem in AEM code with enabling 'BlockSecrets'  hook in github

### ISSUE THREAD

**Issue by shijuc18** [adobe/asset-share-commons#606]
**We have github 'BlockSecrets' going to be enabled org-level. When tested with 'Enabled', looks like some of the files in which  we have secret key or password in,  are prohibited from committing to repository. This include com.day.cq.mailer.DefaultmailService.xml where we have some smtp creds being saved.
What could be the best solution so that enabling 'BlockSecrets' hook will not stop us from committing changes on these files going forward? Since these secrets keys are already encrypted, what additional safety net we can add ? Saving these profile in server is a good approach ?**

* encrypting DefaultmailService.xml so that BlockSecrets enabling will not stop us from committing changes in future on this file.
* Security

**Comment by godanny86** [comment]
hi @shijuc18 if using AEM as a Cloud Service please review this article: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/deploying/configuring-osgi.html

**Comment by davidjgonzalez** [comment]
@shijuc18 and on AEM 6.5 you can use the CryptoService to encrypt/decrypt OSGi properties (encrypted at rest in the file)... don't have the link handy, but if you search experienceleague.adobe.com I think it's in the 6.x docs somewhere.

Alternatively (though I don't recommend it) you can orchestrate the configurations of OSGi components at runtime per-AEM instance via HTTP -> Felix.. this requires a bit of infrastructure, and coordination with deployments, etc.

**Comment by davidjgonzalez** [comment]
Closing as I dont think there are too many other options here.

@bstopp in case he has some thoughts on how to handle secrets management for AEM OSGi config outside of git.
