### ISSUE TITLE
Download archive name by date - timezone specific?

### ISSUE THREAD

**Issue by jstadler1218** [adobe/asset-share-commons#622]
We have set our AEM Cloud Services environment with a download archive name of ${year}${month}${day}${hour.24}${minute}_${asset.count} .
The end user noticed that the hour seems to be in UTC timezone. The question is if there is a way to make this end user timezone specific?

**Comment by davidjgonzalez** [comment]
@jstadler1218 - hmm, i think we need to pass in the user's timezone as part of the request ... 

So pass in `Intl.DateTimeFormat().resolvedOptions().timeZone;` as part of the download POST, and then pass that to the Archive Namer and use that to eval the date/time expressions.

**Comment by davidjgonzalez** [comment]
This is in latest version
