### ISSUE TITLE
Setting up ASC 1.x.x with Maven Project

### ISSUE THREAD

**Issue by tarikzulfikar** [adobe/asset-share-commons#623]
Hi, 

I have AEM 6.5 installed and I am checking out the documentation for setting up ASC 1.9.4 with my existing Maven project generated from AEM Project Archetype. 
This is supposed to be the documentation page for my requirement: [1.x.x Guide](https://opensource.adobe.com/asset-share-commons/pages/development/1-x/guide/) but the content of the page seems to be describing the setup of ASC 2.x.x.

Can someone clarify if I am doing something wrong and where I can find a step-by-step explanation for the setup as I am very new to AEM ecosystem?

Thanks!

**Comment by davidjgonzalez** [comment]
Hi! If you are new user with ASC I strongly recommend using 2.x.x

I will try to locate 1.x docs for you, but please try to use 2.x if possible as 1.x will likely see few updates going forward

**Comment by tarikzulfikar** [comment]
Hi David, 

Thank you for your quick response!

My understanding is that 2.x.x ASC only works with AEM 6.5 SP 1 and above, or AEM as a Cloud Service; neither of which I have access to. 

The infrastructure that we are working on is AEM 6.5 On Premise, so pointers in this direction would be really appreciated.

**Comment by davidjgonzalez** [comment]
Gotcha. I'm stating the obvious, :) but if this is a new project, using asc 2.x is (another) compelling reason to upgrade to a latest 6.5 SP (hopefully latest). I also understand there can be a lot of red tape involved too :) -- but front a strategic project POV aligning to ASC 2.x is definitely the way to go.

When I get to my computer this morning I'll find the 1.x instructions for you though!

**Comment by davidjgonzalez** [comment]
Re-added them, they should be here:

https://opensource.adobe.com/asset-share-commons/pages/development/1-x/guide/

In a few minutes!
