### ISSUE TITLE
Source code for release 1.9.4 is required.

### ISSUE THREAD

**Issue by apoorvvermarics** [adobe/asset-share-commons#626]
**Question?**
* Regarding release version
I want to get source code for release version 1.9.4 but I cant find it now. I can only see 1.9.6 version source now.

Can I please get either release version 1.9.4 or if you can tell what is the difference in 1.9.4 and 1.9.6 as we are using 1.9.4 app package at our end.

Documentation can be found here: https://opensource.adobe.com/asset-share-commons/. It might answer your question!

**Comment by davidjgonzalez** [comment]
Sorry about that - the Git tags for v1.9.2 and v1.9.4 were named incorrectly (or not per convention) and were accidently cleaned up.

Re-added them to the Github releases:

https://github.com/adobe/asset-share-commons/releases

Note that 1.9.6 is the only 1.x release on Maven Central (other 1.x are all on the old repo.adobe.com)
