### ISSUE TITLE
Incorrect dependency type in `assetshare.core` dependency documentation

### ISSUE THREAD

**Issue by madoni** [adobe/asset-share-commons#628]
**Describe the bug**
The [documentation](https://opensource.adobe.com/asset-share-commons/pages/development/deploying/#custom-development-using-asset-share-commons-apis) for "Asset Share Commons APIs" specifies the dependency type as `zip` causing maven error:
`Could not find artifact com.adobe.aem.commons:assetshare.core:zip:2.0.6 in adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public) `

Excluding the type from the dependency specification in the pom seems to resolve this issue.

**Comment by davidjgonzalez** [comment]
Thanks! Fix should be visible momentarily!
