### ISSUE TITLE
downloadStore.removeDownloadId is not a function

### ISSUE THREAD

**Issue by joeri-peeters-emk** [adobe/asset-share-commons#635]
**Describe the bug**
Direct download is enabled. Clicking download opens a new window and successfully downloads the asset. Next step is to remove the downloadById from session store. However, this function doesn't exist.

Download.js (AssetShare.Download)  defines a function removeDownloadById but the download functionality is calling removeDownloadId

https://github.com/adobe/asset-share-commons/blob/c1315317a6a9a26c8d50ae5f1825e33f9ee9453a/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/download.js#L148

https://github.com/adobe/asset-share-commons/blob/c1315317a6a9a26c8d50ae5f1825e33f9ee9453a/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/stores/download-store.js#L112

**Environment**
* AEM Version: N/A
* Asset Share Commons Version: 2.0.6
* Author, Publish or both? both

![image](https://user-images.githubusercontent.com/82503266/130133694-187ece31-c6ed-4d3c-9949-37dd678e178e.png)

**Expected behavior**
Call the right function.

**Comment by davidjgonzalez** [comment]
@joeri-peeters-emk  - hows this look? https://github.com/adobe/asset-share-commons/pull/636/files

Also - thanks for determining the problem and solution :) - made this a very quick fix to execute! 🙌
