### ISSUE TITLE
Uncaught ReferenceError: downloadId is not defined when downloading mp4

### ISSUE THREAD

**Issue by joeri-peeters-emk** [adobe/asset-share-commons#637]
**Describe the bug**
When downloading a mp4, the downloadId is used in a polling function, but it is undefined as it seems(?) it is never set.
The Id is available however in the JS object data.downloadId. Shouldn't it come from there?

<img width="1086" alt="Screenshot 2021-08-20 at 15 59 19" src="https://user-images.githubusercontent.com/82503266/130245273-0abd1ae1-bd4f-4e2c-b75a-0e05501b7ece.png">

<img width="698" alt="Screenshot 2021-08-20 at 16 06 19" src="https://user-images.githubusercontent.com/82503266/130245912-e0ef6f4d-af38-4c05-8672-2b794774fb76.png">

**Environment**
* AEM Version: N/A
* Asset Share Commons Version: 2.0.6
* Author, Publish or both? both

**To Reproduce**
try to download a video (mp4 of couple of 100mb's) not sure if the problem is related to size(?) anyway the id shouldn't be undefined.

**Expected behavior**
Polling function will work using ID.

**Comment by Nishant-Adobe** [comment]
@davidjgonzalez is there any fix for this issue. we are also getting same error (not with mp4) with version 2.1.0

**Comment by joeri-peeters-emk** [comment]
@Nishant-Adobe It seems it's taken up in 2.1.0.
If you need it now, you can override the clientlib with a fix in your own codebase.

**Comment by Nishant-Adobe** [comment]
@joeri-peeters-emk i am using version 2.1.0 only but still same error is coming.
