### ISSUE TITLE
Downloading from Cart not working for assets with special characters in their names (like space).

### ISSUE THREAD

**Issue by dharania** [adobe/asset-share-commons#639]
**Describe the bug**
When user adds an asset to the cart and tries to download it, it fails to download the asset if asset file name (or path) contains special character like space. This seems to to be failing at multiple levels. First, when the javascript [download logic](https://github.com/adobe/asset-share-commons/blob/be8682516e6f33612ea64716f0013e41394aa1eb/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/download.js#L48) serializes the form data for POST request, it encodes the path twice. Because of double encoding, [this](https://github.com/adobe/asset-share-commons/blob/e45e66d77276d1295e34dcaa18934ac60700e727/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/impl/ActionHelperImpl.java#L53) backend logic does not correctly resolve the resource so it can't proceed further. If you somehow get pass that level (by correctly encoding the path), it ultimately fails again giving a url syntax exception.

**Environment**: All
* AEM Version: ? _Latest Cloud Service_
* Asset Share Commons Version: ? _2.0.4/2.0.6_
* Author, Publish or both? _Both_

**To Reproduce**
1. Run a most current version of AEM cloud ready jar on your local
2. Install Asset share commons packages
3. Add an image (that includes a space in it's name) to dam
4. Create a page with Asset Share Commons search template and author it so that it pulls the asset you just added to DAM.
5. On the search page, add the asset to cart and try to download it.
6. You will notice that the asset don't get downloaded.

**Expected behavior**
A zipped file is downloaded when you click on download cart.

**Screenshots**

**Additional context**
ASC download cart feature does not seem to support assets with special characters in the file name, but AEM supports them. It would be really nice if the bug could be fixed in ASC side to it can be utilized by many customers. Currently, we have disabled the cart and download feature because of this issue.

**Comment by davidjgonzalez** [comment]
Thanks @dharania - you are correct!

This build should fix it (there is a SNAPSHOT all package in the comments of it)

https://github.com/adobe/asset-share-commons/pull/640

Do you have other examples of characters that break it that aren't just spaces I could try out?

Thanks!

**Comment by dharania** [comment]
Thanks for the quick fix @davidjgonzalez. I really appreciate it. I will install the package on my local instance and give it a try.  I haven't seen any other unusual characters except for spaces and parentheses (I don't know for sure if it breaks with parenthesis though).

When do you expect to release version 2.1.0?
