### ISSUE TITLE
Site title shows up the component policy title if not authored on header component policy.

### ISSUE THREAD

**Issue by fGhazala** [adobe/asset-share-commons#643]
The Site title shows up the component policy title if not authored on the header component policy.

Environment: AEM cloud instance -author
* AEM Version: 2021.8.5705.20210810T082946Z-210700
* Asset Share Commons Version: asset-share-commons 2.1.0
Group:	asset-share-commons
Filters:	/apps/asset-share-commons-packages
/apps/asset-share-commons-vendor-packages

Author, Publish both

**To Reproduce**
1. Create a page using ASC search page template
2. Edit the header component policy
3. Create a policy with the name "ASC-header-policy" (do not add or update any fields in design dialog)
2. Create a page using that template
3. Author the header component to add at least one nav menu  (do not add or update any fields in component dialog)
4. Check that the Component policy shows up as the site title.

**Expected behavior**
The site title should be empty. The component policy should not show up as the site title.

**Screenshots**
Saving the policy with site title as blank
![image](https://user-images.githubusercontent.com/30626448/132339061-08e45edb-2a43-46bd-90e3-c2b40a9f9ebc.png)
on save, the policy title shows up as the site title
![image](https://user-images.githubusercontent.com/30626448/132339315-c9b0333d-81fb-4a17-bdcf-e81705d2ddde.png)

![image](https://user-images.githubusercontent.com/30626448/132338836-f2a0140d-2218-4599-a393-24050e1cfcba.png)

**Additional context**

The site title and policy fields have the same property name because of which it is fetching the policy title.
![image](https://user-images.githubusercontent.com/30626448/132339477-95646095-6b9c-4bd4-a655-1b502f2f2fb2.png)
![image](https://user-images.githubusercontent.com/30626448/132339696-f2f90823-59f5-4d2f-a9bd-61bd1832904d.png)

at com.adobe.aem.commons.assetshare.components.structure.Header.java
![image](https://user-images.githubusercontent.com/30626448/132340035-b37ca283-2bba-4540-8696-5b57afa696a8.png)

**Comment by davidjgonzalez** [comment]
ahhh @fGhazala ... dang. We should probably select a different property, maybe just `title`,  and then fallback to jcr:title for back compat? ... or can you think of an issue falling back (im suprised this is the first time we've run into this...)

**Comment by fGhazala** [comment]
hey @davidjgonzalez Yes, we should update the site title field on the dialog level and design dialog level. I think it would be good if we follow the existing ASC flow- fetch the site title value from the component dialog and if not authored we get the value from the design dialog, if it is not authored there as well we can keep it empty (and not show the policy title). Or else, if we could add a checkbox on the design dialog level (to fetch the actual site title), if not checked, will not show the site title at all. I think this way we can support both the requirements where we have to show the site title and not to show the site title at all.

**Comment by davidjgonzalez** [comment]
Fixed in 2.1.8 actually (not 2.1.10 per GH milestone)
