### ISSUE TITLE
Uncaught ReferenceError: downloadId is not defined when downloading 

### ISSUE THREAD

**Issue by madhaiya** [adobe/asset-share-commons#644]
**Describe the bug**
When downloading an asset  from download modal with various rendition options selected, the downloadId is used in a polling function, but it is undefined as it seems(?) it is never set.
The Id is available however in the JS object data.downloadId. Shouldn't it come from there?

**Environment**
AEM Version: AEM Cloud Service Environment
Asset Share Commons Version: 2.1.0
Author, Publish or both? : both

**Steps to reproduce the behavior:**
try to download a larger file of any asset (mp4/JPG/JPEG of couple of 10mb's) not sure if the problem is related to size(?) anyway the id shouldn't be undefined. Sometimes download works and most of the time fails to download when multiple renditions options selected and trying to download larger file size.  

**Expected behavior**
Polling function will work using ID.

**Screenshots**
![image](https://user-images.githubusercontent.com/28759788/132500748-a97fef95-f2d0-4a39-a14d-dd5d5876fbe6.png)
![image](https://user-images.githubusercontent.com/28759788/132500821-62cbf524-6707-45f2-b30f-bf634e803eb3.png)
![image](https://user-images.githubusercontent.com/28759788/132501767-08851812-1724-40ea-96aa-9b4dc219cd1c.png)
![image](https://user-images.githubusercontent.com/28759788/132502015-7858ecf3-14b0-4830-b263-00e4d75c2bfa.png)

**Additional context**

**Comment by davidjgonzalez** [comment]
Fixed in 2.1.4
