### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by sarthak-kakkar** [adobe/asset-share-commons#665]
**Describe the bug**
Update readme correct host and port property names, under https://github.com/adobe/asset-share-commons/tree/develop#specifying-crx-hostport.

**Environment**
* Asset Share Commons Version: 2.x

**Expected behavior**
`-Daem.host -Daem.port` should be used instead of `-Dcrx.host -Dcrx.port`

**Comment by sarthak-kakkar** [comment]
Hi @davidjgonzalez 

Was thinking to commit the change instead of adding an issue for it, but I guess there's an approval process around it as per https://github.com/adobe/asset-share-commons/blob/develop/CONTRIBUTING.md, anyhow would be happy to make the change.

Thanks!

**Comment by godanny86** [comment]
ah good catch @sarthak-kakkar, quick PR: https://github.com/adobe/asset-share-commons/pull/666
