### ISSUE TITLE
Index use with property filters

### ISSUE THREAD

**Issue by jstadler1218** [adobe/asset-share-commons#667]
I have worked through an Adobe support case to create regex custom properties as part of damAssetLucene-7 index.
dam:rrd_.*
xmp:rrd_.*

We chose this model as we will have hundreds of custom properties and adding individual properties would create a large ongoing effort for developers and administrators.

In any event, these properties seem to be working well when tested through Explain Query and return expected results. 
**EQ xpath query**:
/jcr:root/content/dam/customer/assets//element(*, dam:Asset)[((_x002e_/jcr:content/metadata/@xmp:rrd_hbi_prefix = '117747'))]

However, when I run the same query through ASC (version 2.1.4) there are NO results returned in the UI. 
**ASC property filter query**:
https://author-redacted.com/en/light.results.html?1_group.propertyvalues.property=.%2Fjcr%3Acontent%2Fmetadata%2Fxmp%3Arrd_hbi_prefix&1_group.propertyvalues.operation=contains&1_group.propertyvalues.values=117747&orderby=%40jcr%3Acontent%2Fmetadata%2Fdc%3Atitle&orderby.sort=asc&layout=card&p.offset=0

My question is related to how the property filters use/select indexes? Is this issue related to the regex index or maybe something else I'm not considering?

**Comment by davidjgonzalez** [comment]
Hi! 
Under the covers, ASC just uses QueryBuilder (as you can somewhat see from the URL format). The (custom) `propertyvalues` predicate is really just a wrapper around QB's `property` predicate to make it a little more suscinct .

I would take a look at the query that ASC's QB is generating and using Explain Query to see what its doing. You can do this one of t 2 ways:

1. Set DEBUG logs on `com.adobe.aem.commons.assetshare.search.impl` package
2.  Use AEM Chrome plugin / Sling Servlet Tracer to "trace" the logs as well as the underlying query/explain query to see how the QB is being evaluated. https://chrome.google.com/webstore/detail/aem-chrome-plug-in/ejdcnikffjleeffpigekhccpepplaode

**Comment by davidjgonzalez** [comment]
closing for now - please re-open if you have more Q's
