### ISSUE TITLE
Asset-Share-Commons sends request for seg.js

### ISSUE THREAD

**Issue by RLMike** [adobe/asset-share-commons#669]
**Describe the bug**
We’re seeing multiple logs for the URL <AEM URL>.seg.js in our Proxy from different users.
We’re seeing that this traffic is coming from Web browser only
Can you please let us know why we’re seeing multiple logs for this domain.

**Production**
* AEM Version: 6.5
* Asset Share Commons Version:  
* Author

**To Reproduce**
N/A

**Expected behavior**
No traffic coming with seg.js

**Screenshots**

**Additional context**

![seg-js-github](https://user-images.githubusercontent.com/92884608/138150339-240c0ef0-fda8-4be6-b8bc-76acb83c4b65.png)

**Comment by davidjgonzalez** [comment]
Closing this. Also, as it occurred to me while going through these issues:

* We removed ASC's USE of contexthub in 2.x
* You can still enable and sue context hub on your ASC pages if you so chose; there's logic in the ASCS page templates that will conditionally toggle the contexthub includes based on if you have a ContextHub config set on the page tree (if you do, that indicates you want to use context hub so the OOTB AEM JS is included)
