### ISSUE TITLE
Downloaded file has incorrect file extension 

### ISSUE THREAD

**Issue by madoni** [adobe/asset-share-commons#670]
**Describe the bug**
For a `.mov` asset, ASC forces the asset extension to `.qt` on download. 

**Environment**
* AEM Version: AEMaaCS (2021.11.6013.20211105T162756Z)
* Asset Share Commons Version: 2.1.2
* Author, Publish or both: Both

**Expected behavior**
I expect a `.mov` asset to download with the same extension.

**Additional context**

When evaluating the file name for download from the user-provided/default filename expression, the[ extension is computed from the mimetype of the asset](https://github.com/adobe/asset-share-commons/blob/1935cb789260f1d17591297c22c0f8ec30d925ef/core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/ExpressionDownloadArchiveNamer.java#L63). 

According to the Sling implementation, the [default extension of `video/quicktime` mimetype is `qt`
](https://github.com/apache/sling-org-apache-sling-commons-mime/blob/master/src/main/resources/META-INF/core_mime.types#L1570)

**Comment by davidjgonzalez** [comment]
As noted this uses the Sling mimeType resolver. Have you looked at registering your own mimeType -> ext mapping  using https://sling.apache.org/apidocs/sling7/org/apache/sling/commons/mime/MimeTypeService.html -> `registerMimeType()`?

Here's some more info on Sling mime type handling (a couple of other extension methods): https://sling.apache.org/documentation/bundles/mime-type-support-commons-mime.html#configuring-mime-type-mappings-1

I don't think we'd want to add to ASC to solve this, since we're intentionally using the Sling framework that should handle all mime-type mapping (don't want to reinvent the wheel).

Can you see if this works?

**Comment by davidjgonzalez** [comment]
Marking as wontfix for now, please reply back is Sling framework isnt sufficient for some reason.

**Comment by madoni** [comment]
@davidjgonzalez Thanks for the information. I did go through the Sling documentation earlier, but it seems that:
> Please note, that existing mappings cannot be overwritten later. 
Most of these mechanisms seem to be for additional mimetypes but not for overwriting existing ones.

Does this mean that I will need to register the quicktime mimetype _before_ the default mappings are applied?

**Comment by davidjgonzalez** [comment]
I could’ve sworn you can overlay some mapping nodes in apps to augment this.. ?

any idea what supports suggests?

**Comment by madoni** [comment]
@davidjgonzalez I'm sorry... I didn't understand your question.

Also, I did try adding the mimetype to the "Apache Sling Commons MIME Type Service" OSGI configuration, but that had no effect. In fact, it quite clearly states in the information for that service that "Existing MIME type mappings cannot be redefined and setting such mappings in this property has no effect".

**Comment by davidjgonzalez** [comment]
@madoni i think we'll have to add a hook for this then - its a bummer we can't extend the MimeTypeService mappings :(

**Comment by madoni** [comment]
@davidjgonzalez ... I saw your update with the fix.... Thank you very much! This did the job!

**Comment by davidjgonzalez** [comment]
Super! Coincidentally I was testing with a bunch of MOV files the other day and saw the same behavior (qt extension) and it confused me for a moment as well until I remembered your issue :)

**Comment by davidjgonzalez** [comment]
Could do that as well! I figure this approach would satisfy all use cases since it can have any logic you want; you can match/key-off on patterns, partials, original file extension, looking up into your own custom lookup table, etc.

**Comment by madoni** [comment]
You're right... this is more than enough for now and solves our immediate issue.

**Comment by davidjgonzalez** [comment]
a PR with your suggestion is welcome! We could put it after this hook but before the sling one!
