### ISSUE TITLE
Remove expired asset from cart

### ISSUE THREAD

**Issue by sumanbi** [adobe/asset-share-commons#676]
I have few expired added in my card, I have removed the download options from all other place except from the cart. Could anyone suggest on how to achieve this functionality.

**Comment by davidjgonzalez** [comment]
IIRC whenever the cart is loaded, it makes a call to AEM to validate that the items in the local storage are infact valid items still (ie they exist and are visible to that user).

When you say "expired" how is this reflected on the asset on AEM Publish? Are you unpublishing the asset? Or are letting the asset to continue to live on AEM Publish, but with an expiry metadata property that is in the past?

**Comment by sumanbi** [comment]
> IIRC whenever the cart is loaded, it makes a call to AEM to validate that the items in the local storage are infact valid items still (ie they exist and are visible to that user).
> 
> When you say "expired" how is this reflected on the asset on AEM Publish? Are you unpublishing the asset? Or are letting the asset to continue to live on AEM Publish, but with an expiry metadata property that is in the past?

The asset is available in the publish , with the expiry metadata property that is in the past.

**Comment by davidjgonzalez** [comment]
@sumanbi Do you only want expired assets removed from the cart, but still visible on the rest of ASC (like share, direct download, asset details, etc.) .. trying to understand why just the cart?
