### ISSUE TITLE
Cloud Manager sonar analysis is failing due to critical issues related with CQRules:CQBP-84

### ISSUE THREAD

**Issue by AbulQasim** [adobe/asset-share-commons#677]
**Describe the bug**

**Environment**
* AEM Version: AEMaaCS
* Asset Share Commons Version: 2.1.12
* Author, Publish or both?

**To Reproduce**
Builds are failing with the following critical sonar issues:
1. The product interface org.apache.sling.api.request.RequestPathInfo annotated with @ProviderType should not be implemented by custom code. Detected in com.adobe.aem.commons.assetshare.util.impl.ExtensionOverrideRequestWrapper$RequestPathInfoWrapper contained in /apps/asset-share-commons-packages/application/install/assetshare.core-2.1.12.jar.

2. The product interface org.apache.sling.api.request.RequestPathInfo annotated with @ProviderType should not be implemented by custom code. Detected in com.adobe.aem.commons.assetshare.content.renditions.download.impl.AssetRenditionDownloadRequest$1 contained in /apps/asset-share-commons-packages/application/install/assetshare.core-2.1.12.jar.

**Expected behavior**
Cloud Manager code analysis is ok

**Actual Behavior**
Cloud Manager code analysis is failing and breaking the build as a result due to Sonar critical issues

**Comment by kelvinxzf** [comment]
@davidjgonzalez would the solution for this one be similar to https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2658?

**Comment by davidjgonzalez** [comment]
FYI - i should have a fix for this ready, i just need to validate it on a real AEM CS to make sure its all still working as expected there.
