### ISSUE TITLE
User configuration issue

### ISSUE THREAD

**Issue by jstadler1218** [adobe/asset-share-commons#678]
**Question?**
When we create "local" AEM users (not managed through Adobe's Managed users tool) for use with ASC site, we experience issues with User Menu on page not recognizing/displaying the username from time to time. This means there is still a "login" link in the upper right of the screen, instead of the logged in user's name and the "logout" link.
* What are you trying to achieve?
The only workaround we have found to date is to unpublish the user (and sometimes the CUG groups) and re-activate/publish them again. Sometimes that fixes the issue and the user is recognized and is displayed with the Logout link, but other times we have to repeat the steps. Other users seem to work right away and don't have issues. 

Are there best practices to creating users and CUGs for use with ASC?

Documentation can be found here: https://opensource.adobe.com/asset-share-commons/. It might answer your question!

**Comment by godanny86** [comment]
@jstadler1218 what version of ASC are you on?

**Comment by jstadler1218** [comment]
2.1.12

**Comment by godanny86** [comment]
Also what version of AEM?

For users that are having issues, do you see any errors in the browser? There should be an ajax request to `/libs/granite/security/currentuser.json` from [0]. I'm curious what the response is for those that are not working... For persistence between navigation for the Cart and downloads we also store some amount of content in the browser storage. Wondering if there is an issue there?

Is the behavior consistent across browsers? Might also be good to try an incognito window as well to see if there is something that gets cached.

On the back-end there shouldn't be anything special for user management for ASC.

[0] - https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/profile.js

**Comment by jstadler1218** [comment]
Latest version of AEM Cloud Services; 2021.12.6151.20211217T120950Z

Yes, I believe we experience across browsers and private windows, but will verify.

I will try the request when we experience the issue and update.
