### ISSUE TITLE
Download component issue

### ISSUE THREAD

**Issue by naveen1048** [adobe/asset-share-commons#685]
Issue triggered while creating proxy for model components(cart and download) from asset share commons.

what are all the clientlibs need to be added for the download component?

we did proxy for download component and on on clicking download we getting error in console as "Uncaught TypeError: Cannot read properties of undefined (reading 'show')" and we getting error as "semanticModal.show([downloadModal]);" in download.js.

**Comment by davidjgonzalez** [comment]
Hi @naveen1048  sorry for the late reply -- it should just be what's defined in the clientlib for the Download component.

https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/.content.xml

You should just need to include use the client category of `asset-share-commons.site.semantic-ui.components.modals.download` and it should pull in everything needed.
