### ISSUE TITLE
Add missing default labels with @ i18N

### ISSUE THREAD

**Issue by gquintillan** [adobe/asset-share-commons#690]
**Is your feature request related to a problem? Please describe.**
Some components are ready for I18N and others not,  for instance:

- Cart component: https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html#L87
- Downloads component: https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/downloads.html#L88

We can see that both components have the same "Close" button but one has the I18N feature `${properties.closeButton || 'Close' @ i18n}` and the other not `${properties['closeButton']}`

**Describe the solution you'd like**
The solution would be to apply the same solution that is already implemented for the Downloads component.

**Describe alternatives you've considered**
The alternative is to create copies for each language and introduce the translations using the provided dialogs

**Comment by NaincyKumariKnoldus** [comment]
Hey @gquintillan Can I do this please? But as I can see  @ i18n in both.

**Comment by davidjgonzalez** [comment]
@NaincyKumariKnoldus that would be great! Well probably try to cut a release sometime this week - so if you can get a PR in, we should be able to merge for release!

**Comment by NaincyKumariKnoldus** [comment]
But as I can see @ i18n in both. then what to change?

**Comment by gquintillan** [comment]
Hi! I'm already working on a PR for this :)
