### ISSUE TITLE
Date fields are not getting mapped correctly

### ISSUE THREAD

**Issue by SmritiMahto** [adobe/asset-share-commons#708]
Hi Team,
We are leveraging ASC URL Asset importer for bulk asset import. We have date format in the excel sheet in MM/DD/YYYY format if the value we input 03/26/2019 the date is coming as 09/26/2008.
Also we are getting many files import failed error, with "Skipped either of the file extension or file size"

Can you please provide us with some inputs on this.

**Comment by davidjgonzalez** [comment]
Think you have the wrong git repo - can you log that here: https://github.com/Adobe-Consulting-Services/acs-aem-commons
