### ISSUE TITLE
to extend the download size limit

### ISSUE THREAD

**Issue by SmritiMahto** [adobe/asset-share-commons#713]
Hi Team,
when downloading the asset of more than 1gb, we get the below error and the download button is also disabled.
Maximum content size of download exceeded Limit 1GB current size is 8.3GB.

We tried changing the limit in the download.html with download.maxContentSize > 30 but is not working.

Is there any other way we can remove/change the download size limit as most of the assets we have are more than 1 GB.

Thanks,
Smriti Mahto

**Comment by davidjgonzalez** [comment]
@SmritiMahto what version of AEM / ASC are you using?

Sounds like AEM 6.x and ASC 1.x  -- can you take a look at the docs here: https://opensource.adobe.com/asset-share-commons/pages/actions/download/1-x/#update-maxcontentsize-for-the-assetdownloadservlet

and see if that fixes your problem?
