### ISSUE TITLE
ContextHub throwing Error in AEM site.

### ISSUE THREAD

**Issue by vihangbhatt** [adobe/asset-share-commons#721]
**Describe the bug**
We utilize contexthub on www.kia.ca AEM website for personalization. Suddenly our contexthub is throwing an error and we have not made any changes.

**Environment**
* AEM Version: AEM Cloud 2022.4.7138.20220427T075748Z
* Asset Share Commons Version: not sure where to look
* Author, Publish or both? both

**To Reproduce**
1. Go to https://www.kia.ca/en/shopping-tools/special-offers
2. Click on open chrome inspector and there is a error logged in the console and as you can see in the screenshot the legal copy is not loading.

**Expected behavior**
The legal copy on the special offers page should be loading based on the province selected in the footer but it doesn't work for any provinces currently and throwing some error.

**Screenshots**

![contexthub_error](https://user-images.githubusercontent.com/104858625/166513849-a5fd058b-5c9c-4dde-b005-404fcec7b87c.png)

**Comment by davidjgonzalez** [comment]
This doesnt appear to be an Asset Share Commons implementation. I suggest you log an issue with Adobe Support.

Please let me know if this is Asset Share Commons releated and im somehow missing it - thanks!

**Comment by keepthebyte** [comment]
Please use CH-279 as reference when contacting Adobe Support. Thanks.
