### ISSUE TITLE
Download, Share and Cart buttons are not working in Asset Share Commons Publish page

### ISSUE THREAD

**Issue by anjuathakur** [adobe/asset-share-commons#727]
Download, Share and Cart buttons are not working in Asset Share Commons Publish page while it is working fine in Author Instance of AEMaaCS

We have tried below solutions to resolve it but its not working

>>Checked read permissions (to the everyone user for the anonymous use case) on:

/conf/xxx/wcm/settings/templates
/conf/xxx/wcm/settings/policies
/etc/cloudsettings

>> Checked the dispatcher codes
>> Published the pages/templates

Its a blocker for us and impacting the production go live

**Comment by anjuathakur** [comment]
Kindly confirm if you have faced this in past or have some guidance around the solution

**Comment by godanny86** [comment]
hi @anjuathakur can you expand on not working? Is it a 404 error for the partial modal `.html` request or is it a javascript error? Can you share the browser console and the network requests tab using dev tools?

**Comment by Jaski96** [comment]
Hi @godanny86, there are no errors in console
Here are the issues: 
**AUTHOR:**
1. The assets  share details are displayed when clicking the SHARE button.
2. Cart modal contains the details of the assets that are added to the cart.
3. DOWNLOAD button is working.   
![image](https://user-images.githubusercontent.com/105772836/168974117-65b1116f-5692-4f14-9afb-02d0e1fa0081.png)
![image](https://user-images.githubusercontent.com/105772836/168974235-d680f959-b1b5-4448-a19f-0d0e9ce245b1.png)

**PUBLISH:**
1. The assets  share details are missing when clicking the SHARE button.
2. Cart modal is empty.
3. DOWNLOAD button is not working.
![image](https://user-images.githubusercontent.com/105772836/168974295-e3115e5a-125a-4575-b4b7-6f02fecc8d25.png)
![image](https://user-images.githubusercontent.com/105772836/168974328-bf71d16a-ca58-4c2b-8f85-0ba5ec25d4c0.png)

Here's Network tab when clicking share button:
![image](https://user-images.githubusercontent.com/105772836/168975950-fa7c1b8c-3cec-48ea-b85d-aa6859c9f89f.png)

**Comment by godanny86** [comment]
What version of AEMaaCS?
What version of AssetShare Commons?

Can you look at the parameters of the POST request to the `.partial.html`? Are the asset paths being sent?

**Comment by godanny86** [comment]
The payload for the POST request for Cart, Download, Share should all look something similar to this:

![image](https://user-images.githubusercontent.com/8974514/169152744-f53ad7f8-c7f1-4244-a2a2-636b5644b159.png)

**Comment by davidjgonzalez** [comment]
Assuming a list of paths is being sent, i have to image they're not able to be converted to AssetModels in this logic:

https://github.com/adobe/asset-share-commons/blob/master/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/impl/ActionHelperImpl.java#L54-L63

```
        return Arrays.stream(requestParameters)
                    .filter(Objects::nonNull)
                    .map(RequestParameter::getString)
                    .filter(StringUtils::isNotBlank)
                    .map(path -> Text.unescape(path))
                    .map(path -> request.getResourceResolver().getResource(path))
                    .filter(Objects::nonNull)
                    .map(resource -> modelFactory.getModelFromWrappedRequest(request, resource, AssetModel.class))
                    .filter(Objects::nonNull)
                    .collect(Collectors.toList());
```

**Comment by Jaski96** [comment]
Hi @godanny86, We are using ASC v2.2.0-1
The payload for the POST request for Cart, Download, Share is same for us.
![image](https://user-images.githubusercontent.com/105772836/169214522-45d8349d-dbbc-4f7e-8249-72a9cf20e946.png)

**Comment by davidjgonzalez** [comment]
@Jaski96 Were you able to uncover anything else WRT this issue?

**Comment by davidjgonzalez** [comment]
Closing - but please re-open if you are still experiencing this problem/can provide more details.
