### ISSUE TITLE
Different asset detail page displayed for the same asset on author and publish

### ISSUE THREAD

**Issue by kwin** [adobe/asset-share-commons#747]
**Describe the bug**
The "Add to cart" button in the asset details is missing for PDF on publish, while it is there on author

**To Reproduce**
1. Go to https://aem.enablementadobe.com/content/asset-share-commons/en/light/details.html/content/dam/asset-share-commons/en/public/documents/document-sample.pdf
2. See the action "Add to cart" is missing

**Expected behavior**
The same actions as for https://aem.enablementadobe.com/content/asset-share-commons/en/light/details/document.html/content/dam/asset-share-commons/en/public/documents/document-sample.docx should be provided as this is also the details page which is used on Author.

**Screenshots**
![Screenshot 2022-06-13 at 19 43 08](https://user-images.githubusercontent.com/185025/173412992-cf5a7498-e9e2-4b76-965d-77343440bf52.png)

**Comment by kwin** [comment]
It is not clear to me which of the conditions from https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/action-buttons/action-buttons.html may differ by actual asset (and its type).

**Comment by davidjgonzalez** [comment]
@kwin  

+ `properties['addToCartLabel']` 
+ `properties['removeFromCartLabel']` 

...are both component properties

And `config.cartEnabled` is configured on the parent ASC Search page's page properties (there's some paths to the Cart modal, and the  checkbox).

... So the first 2: 

+ `properties['addToCartLabel']` 
+ `properties['removeFromCartLabel']` 

Could differ by asset type, assuming those asset types have different Asset Details pages.

**Comment by kwin** [comment]
@davidjgonzalez Thanks for the hints, indeed different asset details pages are used. The reason for this seems to be https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/AssetTypeImpl.java#L79 which returns "DOCUMENT" for the docx asset but not for the PDF with {{dc:type}} being {{application/pdf}}. IMHO PDF should also be classified as "DOCUMENT". WDYT?

**Comment by kwin** [comment]
This duplicates issue #714
