### ISSUE TITLE
assetshare.ui.config not deployed to Maven Central

### ISSUE THREAD

**Issue by kwin** [adobe/asset-share-commons#761]
The newly added Maven module "assetshare.ui.config" is not deployed to Maven Central. https://repo1.maven.org/maven2/com/adobe/aem/commons/ does not contain any "assetshare.ui.config" directory. Seems that the release process was not adjusted accordingly.

**Comment by davidjgonzalez** [comment]
@kwin thanks - is the breaking the use of the latest dependency (due to the transitive dep resolution of the all package?)

**Comment by kwin** [comment]
I don't want to use the `all` package in my own container package, instead I am referencing the individual packages and bundle, as otherwise I cannot resolve the package dependency on `assetshare.ui.apps`. When using the `all` container package directly it will probably work (as Maven does not need to resolve `assetshare.ui.config` in that case).

**Comment by davidjgonzalez** [comment]
Gotcha - was more curious if it in fact did break builds depending on `all` (i think it will) - we of course need to release all artifacts.

**Comment by davidjgonzalez** [comment]
ui.config is available with 2.3.2

https://search.maven.org/artifact/com.adobe.aem.commons/assetshare.ui.config
