### ISSUE TITLE
'/apps/asset-share-commons/config*' not removed when upgrading to 2.3.x leading to stale OSGi config

### ISSUE THREAD

**Issue by kwin** [adobe/asset-share-commons#770]
The OSGi configuration has been relocated from `/apps/asset-share-commons/config*` to `/apps/asset-share-commons/osgiconfig/config*` in https://github.com/adobe/asset-share-commons/pull/739/files#diff-dd8289beea0069c67b98e3a133f49e1f73ae6a3f955668761e7a7487f700c3ca. The filter rule in https://github.com/adobe/asset-share-commons/pull/739/files#diff-56cf2c22fe3a5c458503f6aa32a4b79b48f83e57bdb6c5d88fc972fd5ced82cdL3 does no longer cover the old paths, therefore the old configuration nodes are not removed when upgrading to 2.3.x.

In my case that leads to the case that the wrong repoinit config is still active which does not contain the newly added service user.

**Comment by kwin** [comment]
Here is a list of nodes, which have been created prior 2.3.0: https://github.com/adobe/asset-share-commons/tree/a3701943d5116996f391dad2148fe17967ef6b14/ui.apps/src/main/content/jcr_root/apps/asset-share-commons

**Comment by davidjgonzalez** [comment]
Thanks @kwin !
