### ISSUE TITLE
Download cart is not working for video assets in publisher

### ISSUE THREAD

**Issue by udaykumarAEM** [adobe/asset-share-commons#784]
Download cart is not working for video assets in publisher.
It is working in the author though.
could not see the error logs for this issue.
The response error code is 504 for the request in the page
The asset share Commons version is 1.9x and we are using AEMaaCS latest version.

**Comment by davidjgonzalez** [comment]
You must use ASC 2.x for AEMaaCS. Please use latest as there have been a few bug fixes for CS since 2.0.0

**Comment by davidjgonzalez** [comment]
If you continue to have issues using the latest ASC 2.x on AEMaaCS please re-open w/ details.
