### ISSUE TITLE
We are getting below error in the console for the cart store.

### ISSUE THREAD

**Issue by Lovekeshgoel** [adobe/asset-share-commons#802]
Hi,

We are getting below on the console in every page of asset share common.

We have migrated to Asset Share Common of the version 2.0.6

PFA of the error

![image](https://user-images.githubusercontent.com/111757113/185952560-116f18a3-cf22-4d1d-9151-c066e2fab205.png)

![image](https://user-images.githubusercontent.com/111757113/185952699-0779737f-d65e-410d-9f81-cb9c1ccaf3b6.png)

Thanks
Lovekesh Goel

**Comment by Lovekeshgoel** [comment]
@davidjgonzalez Can you please check this once?

**Comment by davidjgonzalez** [comment]
Is this an old version of ASC? We replaced the use of contexthub some time ago.

**Comment by Lovekeshgoel** [comment]
We have developed the application on lower version. Now we have migrated to new version 2.0.6. But we are not exactly sure how to handle this above error as Asset Share Common change has been done.

**Comment by davidjgonzalez** [comment]
@Lovekeshgoel it looks like youre somehow using ASC v1 JavaScript (cart-badge.js) with some ASC v2 javascript? Did you copy-down some v1 JavaScript into your case base at some point? If you did youll need to update it to use v2.

As you can see, that error'ing line was removed https://github.com/adobe/asset-share-commons/commit/9eb48cbf0c19a9e8a3e8c0f4d00e98ea3a963136#diff-a01c5c16d5e722190d532cdda913ad698a10eb7960359ff8729ac2ef4876a211L40 when ContextHub was removed.

Can you provide more details of how you've incorporated ASC into your project? (did you copy ASC source code into your project, did you include the maven dependencies as described in ASC docs? some mix?)

**Comment by kiranGuptaInfy** [comment]
Hi @davidjgonzalez, we have some list of assets in our database and we want to display these assets using ASC with download & share, sorting and load more functionality. Is there any way we can implement it? 
Please help us.
Its really urgent .
Thanks in advance.
Waiting for your response

**Comment by davidjgonzalez** [comment]
@Lovekeshgoel im going to close this, but please feel free to re-open if you have more info/require further clarification.
