### ISSUE TITLE
We are facing one more issue on share functionality for Documents

### ISSUE THREAD

**Issue by Lovekeshgoel** [adobe/asset-share-commons#803]
Hi Team,

When we share any document from asset share common it is going to the wrong URL.

PFB the URL :- [/asc/en/home/details.html/content/dam/multisite/fendt/parts/multi-region/documents/testMRMstock5.pdf]

It should be coming like this

[/asc/en/home/details/document.html/content/dam/multisite/fendt/parts/multi-region/documents/testMRMstock5.pdf]

For Image and Video it is working fine. We have not changed anything in asset share common.

Can you please help us why it is happening.

Thanks
Lovekesh Goel

**Comment by davidjgonzalez** [comment]
@Lovekeshgoel - sorry for the delay! I was out on holiday last week!

The Details page is selected using the AssetType computed property (it takes that value, lower-cases it and turns spaces to -, IIRC) .. so it sounds like the PDF asset type does not equal "document".

The asset type is computed based on some "internal" AEM logic .. .but as you can see on the ASC demo site, the "Asset type" of a pdf file is actually "PDF" (and not "Document") .. so if you make a details page named "pdf" it should resolve to that.

![2022-08-29 at 11 21 AM](https://user-images.githubusercontent.com/1451868/187236093-73df1c38-39cd-42b8-b308-1235983a6e85.png)


 If you want the same Details page, you can implement a custom [AssetDetailsSelector OSGi component](https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/selectors/AssetTypeSelectorImpl.java), and have it build the details URL using whatever logic you want - you can select the AssetDetailsSelector to use (once you deploy yours) via the [Search Page properties](https://opensource.adobe.com/asset-share-commons/pages/search/search-page/).
