### ISSUE TITLE
Version 2.4.0 not available in Maven Central

### ISSUE THREAD

**Issue by kwin** [adobe/asset-share-commons#818]
Maven Central does not have the most recent version 2.4.0 (https://repo1.maven.org/maven2/com/adobe/aem/commons/assetshare/).

**Comment by davidjgonzalez** [comment]
@kwin it appears to be in the oss release repo.

i've logged an issue w/ them inquiring why it hasnt made it to maven central yet: https://issues.sonatype.org/browse/MVNCENTRAL-7623

**Comment by kwin** [comment]
I see, finally Sonatype confirmed there is an issue at https://status.maven.org/incidents/wk2ylsb6byc3.

**Comment by davidjgonzalez** [comment]
Looks like its there now:

https://repo1.maven.org/maven2/com/adobe/aem/commons/assetshare.all/2.4.0/
