### ISSUE TITLE
Content package has malformed XML

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/asset-share-commons#819]
**Describe the bug**

It's reported the content package exhibits this error:

[content-packages-validation] asset-share-commons:asset-share-commons.ui.apps:zip:cp2fm-converted:2.3.4: ValidationViolation: "jackrabbit-docviewparser: Could not parse FileVault Document View XML: Unknown namespace prefix used in file name 'cq:template'", filePath=jcr_root/apps/asset-share-commons/components/modals/download/_cq_template/.content.xml, nodePath=/apps/asset-share-commons/components/modals/download/cq:template, line=32, column=127\

**Environment**
* AEM Version: CS
* Asset Share Commons Version: 2.3.4
* Author, Publish or both? BOTH

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kwin** [comment]
This indicates not really malformed XML as the undeclared namespace is only used in the filename. Compare with https://github.com/adobe/aemanalyser-maven-plugin/pull/163#issuecomment-1165399863 and https://issues.apache.org/jira/plugins/servlet/mobile#issue/JCRVLT-639.

**Comment by davidjgonzalez** [comment]
Thanks @kwin - so looks like we can update the FV plugin version to resolve this.

**Comment by kwin** [comment]
I am not sure this error really came from Maven or from the additional validation steps being performed by Cloud Manager.
If it is the former most probably an update of the aem-analyser-maven-plugin would be necessary, if it is the latter, then cp2fm would require an update. Both things are outside of this project's scope...
