### ISSUE TITLE
We are not able to install the asset share common package on local

### ISSUE THREAD

**Issue by Lovekeshgoel** [adobe/asset-share-commons#826]
**Describe the bug**
While installing the asset share common version 2.1.12 on AEM local it is not working. The bundle is not getting activated.

**Environment** LOCAL
* AEM Version: 6.5.11 
* Asset Share Commons Version: 2.1.12
* Author, Publish or both? on Author

PFB the screenshot for the same :- 

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/111757113/197499484-6345e67d-4ee1-48a5-a745-fb6326b6df80.png)

Please tell us why it is happening. We are also installing ACS AEM commons with version 5.0.6.
Its a fresh instance without any project code.

**Comment by Lovekeshgoel** [comment]
Resolved

**Comment by davidjgonzalez** [comment]
For posterity, it appears core components were not installed. ASC requires core components to be installed.
