### ISSUE TITLE
& Is converting into &amp while typing the optional message in share funtionality.

### ISSUE THREAD

**Issue by Lovekeshgoel** [adobe/asset-share-commons#866]
Hi Team,

We typed ' !@#$%^&*-+ ' in the optional message while sharing the asset.

We saw in the outlook the message is appearing in the email is ' !@#$%^&amp;*-+ '  After & it is appending with amp; which you can't see in the comment.

I am not sure why it is happening. Can you please tell me to handle it.

Thanks
Lovekesh Goel

**Comment by alishapoddar18** [comment]
@davidjgonzalez @Lovekeshgoel 
We are using an HTML template only instead of plain text. Everything is within html tags only

**Comment by alishapoddar18** [comment]
@davidjgonzalez
Any update on this. Do you need any more information?

**Comment by kirnGuptaa** [comment]
Hi @davidjgonzalez,
Can you please update on same.
Thanks in advance.

**Comment by davidjgonzalez** [comment]
v2.4.8 should have the fix for this (released yday)
