### ISSUE TITLE
Asset share components are not working in publisher

### ISSUE THREAD

**Issue by jmzcray** [adobe/asset-share-commons#867]
Firstly, our current setup:
AEM: 6.5.14
asset share commons: 2.4.4
WCM core components: 2.21.2

The problem we are having now is limited to publisher only. All the asset share components aren't working and it seems to be related to unable to get userProfile from /libs/granite/security/currentuser.json.

In the the browser developer console, it is throwing an error of:
`Uncaught TypeError: Cannot read properties of undefined (reading 'get')`

in this file:
https://github.com/adobe/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/profile.js#L41 

Is there anything to resolve this? Is it related to how AEM publisher needs ?sling:authRequestLogin=1 to login to publisher?

**Comment by jmzcray** [comment]
My apologies! The ASC version that was installed is 2.4.4 instead...

**Comment by davidjgonzalez** [comment]
Can you check if 'jQuery' is a global object? (Check if that var exists in the window by typing it into your browser console).. I think that error is saying that jquery is undefined .. which would definitely break a lot of stuff

**Comment by jmzcray** [comment]
Yes, jQuery is undefined and I am not sure why...

If I revert ACS back to 1.8.0 everything works again.

**Comment by jmzcray** [comment]
I think it relates to this error in the browser developer console:
`No suitable store implementation found for type: "contexthub.assetsharecommonscart".` 

But I can't find anything that address this anywhere...

**Comment by jmzcray** [comment]
Update, I can see a reference to "contexthub.assetsharecommonscart" in node: 
/etc/cloudsettings/asset-share-commons/contexthub/cart

However, that node is created from ASC 1.8.0. 

In ASC 2.4.4 there is nothing equivalent to that. So far, I can't see anywhere on where to address this issue when upgrading from 1.x to 2.x for ASC...

**Comment by jmzcray** [comment]
Update:

I've uninstall ASC 2.4.4 and 1.8.0, then reinstall ASC 2.4.4 and the problem still exist...

This time, there is no error about "contexthub.assetsharecommonscart".

The error now (which also present before uninstalling 1.8.0 and reinstalling 2.4.4) in the browser developer console is:
`clientlib-dependencies.min.js:142 Uncaught TypeError: Cannot read properties of undefined (reading 'html5')`

pointing at the code in modernizr-2.8.3.min.js at:
https://github.com/Modernizr/Modernizr/blob/v2.8.3/modernizr.js#L1016 

Is there anyone else that can help?

**Comment by jmzcray** [comment]
ok... looks like my issue is related to: https://github.com/adobe/asset-share-commons/issues/856
