### ISSUE TITLE
404 link 

### ISSUE THREAD

**Issue by bartoszWesolowski** [adobe/asset-share-commons#876]
On [Carts documentation page](https://opensource.adobe.com/asset-share-commons/pages/actions/cart/#:~:text=Search%20page%E2%80%99s%20Page%20Properties%E2%80%99%20Personalization%20tab.) in the Contexthub section `[Search page’s Page Properties’ Personalization tab](https://opensource.adobe.com/asset-share-commons/pages/actions/search/#page-properties).` points to 404.

**Comment by davidjgonzalez** [comment]
Fixed! thanks - updated to note that ASC v2.x.x no longer uses Context Hub to manage the Cart.
