### ISSUE TITLE
Query Traversal Issue while Accesing the Asset Share common Home Page 

### ISSUE THREAD

**Issue by bhausahebkhamat** [adobe/asset-share-commons#884]
**Describe the bug**
While Accessing the Custom Asset Share Common Home Page, we are getting a query Traversal issue as below.
**Is the query traversal issue addressed in any new version after 2.2.0 release?**

```
org.apache.jackrabbit.oak.plugins.index.cursor.TraversingCursor Traversed 95000 nodes with filter Filter(query=select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/accenture/final') /* xpath: /jcr:root/content/dam/xxx/final//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by @jcr:score descending */, path=/content/dam/accenture/final//*, property=[jcr:content/contentFragment=[is null]]) called by com.adobe.aem.commons.assetshare.search.providers.impl.QuerySearchProviderImpl.getResults; consider creating an index or changing the query
```

![image](https://user-images.githubusercontent.com/8667700/210386045-27c7e60c-ebfe-429d-bac5-7085460e90b4.png)

**Environment**
* AEM Version: 2022.9.8630.20220905T184657Z-220800
* Asset Share Commons Version: 2.2.0
* Author, Publish or both : Publish

**Comment by davidjgonzalez** [comment]
1. Did this just start when updating to `2022.9.8630.20220905T184657Z-220800` ? Do you recall what version of AEM CS is didnt throw this error on?
1. Does this happen on AEM Author? or ONLY AEM publish?
2. Is this on AEM SDK or AEM CS Cloud? (or both)
3. Are you deploying custom index updates to the damAssetLucene index?

**Comment by davidjgonzalez** [comment]
@bhausahebkhamat i checked on my AEM AUthor running 2022.9.8630.20220905T184657Z-220800 and my it resolves to an index (i have to make the path map to an existing path for it to use an index; since oak is smart enough to know what filtering on a non-existant path will always yield 0 results.)

```[dam:Asset] as [a] /* lucene:damAssetLucene-8(/oak:index/damAssetLucene-8) :ancestors:/content/dam where ([a].[jcr:content/contentFragment] is null) and (isdescendantnode([a], [/content/dam])) */
```

Can you attach your explain query logs for AEM CS that is exhibiting this?  Note that I didnt do this on AEM Publish since its takes some work to get Dev Console access setup for AEM Pub.

**Comment by bhausahebkhamat** [comment]
Did this just start when updating to 2022.9.8630.20220905T184657Z-220800 ? Do you recall what version of AEM CS is didnt throw this error on?  **We have the same version available in lower env. and its working over there** 

Does this happen on AEM Author? or ONLY AEM publish? **Only on Publish** 

Is this on AEM SDK or AEM CS Cloud? (or both)  **AEM CS Cloud** 

Are you deploying custom index updates to the damAssetLucene index? **Yes but not specifically for Asset Share common** 


**Please find the below logs as well** 

Parsing JCR-SQL2 statement: explain select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/.../final') cost using filter Filter(query=explain select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/.../final'), path=/content/dam/.../final//*, property=[jcr:content/contentFragment=[is null]]) cost for reference is Infinity cost for property is Infinity cost for nodeType is Infinity Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: dam:Asset Applicable IndexingRule found IndexRule: dam:Asset Applicable IndexingRule found IndexRule: dam:Asset Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:hierarchyNode Applicable IndexingRule found IndexRule: nt:base Applicable IndexingRule found IndexRule: nt:base cost for [/oak:index/assetPrefixNodename-1] of type (lucene-property) with plan [lucene:assetPrefixNodename-1(/oak:index/assetPrefixNodename-1) :ancestors:/content/dam/.../final] is 13714600000.00 cost for [/oak:index/damAssetLucene-8-custom-10] of type (lucene-property) with plan [lucene:damAssetLucene-8-custom-10(/oak:index/damAssetLucene-8-custom-10) :ancestors:/content/dam/.../final] is 126980.00 cost for lucene-property is Infinity cost for elasticsearch is Infinity cost for aggregate lucene is Infinity looking for plans for paths : [] cost for aggregate solr is Infinity cost for traverse is 8430692.0



**Explain Query JSON**

{
    "statement": "select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/.../final')",
    "language": "JCR-SQL2",
    "explain": {
        "logs": [
            "Parsing JCR-SQL2 statement: explain select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/.../final')\n",
            "cost using filter Filter(query=explain select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/.../final'), path=/content/dam/.../final//*, property=[jcr:content/contentFragment=[is null]])\n",
            "cost for reference is Infinity\n",
            "cost for property is Infinity\n",
            "cost for nodeType is Infinity\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: dam:Asset\n",
            "Applicable IndexingRule found IndexRule: dam:Asset\n",
            "Applicable IndexingRule found IndexRule: dam:Asset\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:hierarchyNode\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "Applicable IndexingRule found IndexRule: nt:base\n",
            "cost for [/oak:index/assetPrefixNodename-1] of type (lucene-property) with plan [lucene:assetPrefixNodename-1(/oak:index/assetPrefixNodename-1) :ancestors:/content/dam/.../final] is 13714500000.00\n",
            "cost for [/oak:index/damAssetLucene-8-custom-10] of type (lucene-property) with plan [lucene:damAssetLucene-8-custom-10(/oak:index/damAssetLucene-8-custom-10) :ancestors:/content/dam/.../final] is 126979.00\n",
            "cost for lucene-property is Infinity\n",
            "cost for elasticsearch is Infinity\n",
            "cost for aggregate lucene is Infinity\n",
            "looking for plans for paths : []\n",
            "cost for aggregate solr is Infinity\n",
            "cost for traverse is 8430692.0\n"
        ],
        "plan": "[dam:Asset] as [a] /* lucene:damAssetLucene-8-custom-10(/oak:index/damAssetLucene-8-custom-10) :ancestors:/content/dam/.../final where ([a].[jcr:content/contentFragment] is null) and (isdescendantnode([a], [/content/dam/.../final])) */",
        "propertyIndexes": [
            "damAssetLucene-8-custom-10(/oak:index/damAssetLucene-8-custom-10)"
        ]
    },
    "heuristics": {
        "results": [
			............
			............
			............
				
		   ],
        "count": "20+",
        "readPageTime": 119,
        "executionTime": 2,
        "getNodesTime": 119,
        "totalTime": 121
    }
}

**Comment by davidjgonzalez** [comment]
@bhausahebkhamat  the query explanation shows that `/oak:index/damAssetLucene-8-custom-10` is being used.  .. So im not sure how this is traversing. Was the explain from AEM Author? Or AEM Publish?

Either way, it looks like your AEM Publish doesnt have a index that can satisfy this query (it should). You might need to engage with Adobe Customer Care to understand why your query isn't finding an index. 

I recommend logging the Customre Care issue specifically around the query 

````
select [jcr:path], [jcr:score], * from [dam:Asset] as a where [jcr:content/contentFragment] is null and isdescendantnode(a, '/content/dam/.../final')
```

Not resolving to an index, and not mentioning Asset Share Commons - since they dont support Asset Share Commons, and its mention may confuse them as to what the actual, underlying problem is (which is that query cannot resolve to a index on AEM CS Publish).

**Comment by Hanzley** [comment]
Besides using index, is it feasible to add 100 limit in the XPath being generated by the  query builder:

query ROOT=group: limit=24, guessTotal=100, offset=0[_    {orderby=orderby: orderby=@jcr:score, sort=desc}_    {type=type: type=dam:Asset}_    {2_group=group: or=true[_        {0_path=path: path=/content/dam/.../final}_    ]}_    {4_group=group: [_        {property=property: property=jcr:content/contentFragment, operation=not}_    ]}_]

XPath being generated by the code com.day.cq.search.Query.getResult(): 

/content/dam/.../final//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by @jcr:score descending

This is the preferred XPath query:
/content/dam/accenture/final//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by @jcr:score descending _option(limit 100)_

The goal with this XPath query is to optimize the initial loading of the search page containing the ASC Search Result component by limiting the asset to 100.

**Comment by davidjgonzalez** [comment]
Can you set the search results component's guesstotal field?

https://opensource.adobe.com/asset-share-commons/pages/search/results/

Or do you need to change guesstotal based on first load Vs subsequent?

**Comment by Hanzley** [comment]
Yes,  I was able to set the guess total as you can see in the query generated by the query builder above (**guessTotal=100**), but when i check the debug log, the equivalent XPath query statement does not include the **_option(limit 100)_**  (_captured by searchResult.getQueryStatement() in the debugPostQuery method_). This made me wonder if the SearchResult object does really apply the limit.

**Comment by davidjgonzalez** [comment]
Closing this for now. Please re-open if you are still effected
