### ISSUE TITLE
Free form text filter not working as expected

### ISSUE THREAD

**Issue by RahulMohann** [adobe/asset-share-commons#895]
We are using free form text filter with operator selected as 'Contains'. But it is not giving results while searching using that filter. Could you please advise?

**Environment**
* AEM Version: AEM as Cloud Service
* Asset Share Commons Version: 2.3.4
* Author, Publish or both: Both

**To Reproduce**
1. Configure free form text filter.
2. Select operation as 'Contains'.
3. Search with some metadata value available in any asset.
4. No results found.

![image](https://user-images.githubusercontent.com/99810531/217850809-e591c0ac-4f68-41ad-98bd-74d01d0c18e6.png)

**Comment by davidjgonzalez** [comment]
@RahulMohann  do you have any idea the contains works in a "raw" QueryBuilder query for that properyt?

I believe you have to make sure its index rule is "analyzed=true" for it to be searchable directly via contains(..)

https://jackrabbit.apache.org/oak/docs/query/lucene.html

**Comment by RahulMohann** [comment]
Hi David,

Thanks for the update. I've added the 'analyzed=true' property for the text field and reindexed. Then the 'contains search' worked fine in my local AEM instance. However I tried the same in our cloud dev AEM instance. Unfortunately it is not working there. Even in the query builder also, it's not returning any results. Any clue on that?

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
If it works on SDK, then it sounds like your analyzed=true change isn't getting picked up in the cloud. 

Can you use explain query in cloud service (via cloud manager > the env > developer console > query) to see what index the query resolves to, and that that index is in fact your customized index. Remember you need the special index naming convention in cloud service and the index must be deployed via your project/cloud manager.

**Comment by RahulMohann** [comment]
Hi David,

Yes, that was the issue. When I configured the index correctly it worked.

Thank you
Rahul

**Comment by davidjgonzalez** [comment]
Thanks for confirming @RahulMohann !
