### ISSUE TITLE
ContextHub is not defined

### ISSUE THREAD

**Issue by amanmishra17** [adobe/asset-share-commons#903]
Hi Team, 
We are getting a console error **"ContextHub is not defined"** on search page when coming back from the asset details page. We are not sure why it comes up randomly. Attached the screenshot of error for the reference.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/42470428/218818915-c2f82433-2b85-4877-88c4-5e3d2fec1273.png)

Any input to resolve this would be very helpful. 
Thanks.

**Comment by davidjgonzalez** [comment]
Not sure - 1.9 hasnt changed in years. Maybe something has changed in AEM that is breaking this?

Can you update to ASC v2?

**Comment by davidjgonzalez** [comment]
Please reopen if you are still having the issue.
