### ISSUE TITLE
Asset Share functionality asset path formation

### ISSUE THREAD

**Issue by SmritiMahto** [adobe/asset-share-commons#907]
Hi Team,
We have configured share component for our asset sharing functionality, but the asset path formed is localhost:4502 and then the asset path. We did search in the code the url formation for the same but we couldn't find one. Can you please let us know on how can we append our host url for the asset share.

Thanks,
Smriti Mahto

**Comment by davidjgonzalez** [comment]
This should be using the OOTB AEM externalizer to form the url.

https://experienceleague.adobe.com/docs/experience-manager-64/developing/platform/externalizer.html?lang=en

**Comment by SmritiMahto** [comment]
can we add an externalizer configuration file, as in stage when we try clicking the asset path link in the share email it takes us to localhost:4503 sign in and we want out own host url in the email asset path link.

Thanks,
Smriti Mahto

**Comment by davidjgonzalez** [comment]
@SmritiMahto im not sure i follow - if you configure the AEM Externalizer configuration, and deploy that config to your AEM Publish service (making sure it's targetting the active runmodes of that Pub service) then the Hosts should be whatever you configure them. Can you verify that the the right values are bound to the OOTB AEM Externalizer OSGi component and/or test out that a call to the AEM Externalizer OSGi service is prefixing URLs with the correct host?

**Comment by davidjgonzalez** [comment]
@SmritiMahto  please make sure to provide the version of Asset Share Commons you are using int he issue as well.

**Comment by davidjgonzalez** [comment]
Please reopen if you are still having the issue.
