### ISSUE TITLE
Documentation needs to be more clear

### ISSUE THREAD

**Issue by alisonasanchez** [adobe/asset-share-commons#909]
The doc https://opensource.adobe.com/asset-share-commons/pages/getting-started/set-up/ talks about logging a ticket with support to set up email for AEMaaCS. It's not super clear what needs to be done, but setting up email on AEMaaCS is self service and you should direct them to this document instead of logging a case:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking.html

**Comment by davidjgonzalez** [comment]
Thanks! Updated the doc
