### ISSUE TITLE
Security Vulnerability in moment.js

### ISSUE THREAD

**Issue by Arun-Rangasamy** [adobe/asset-share-commons#911]
Our security scan report is alerting us to upgrade the moment.js(2.29.3) version provided as part of the latest release [asset-share-commons-2.5.4] to the moment.js(2.29.4). 

Vulnerability:
Regular Expression Denial of Service (ReDoS)
Affecting moment package, versions >=2.18.0 <2.29.4

Can you please help us with when can we get moment.js upgrade in the release?

**Comment by Arun-Rangasamy** [comment]
@davidjgonzalez, Can you please provide your insights on this?

**Comment by davidjgonzalez** [comment]
Fixed in https://github.com/adobe/asset-share-commons/pull/978

**Comment by davidjgonzalez** [comment]
Fixed in: https://github.com/adobe/asset-share-commons/releases/tag/asset-share-commons-3.4.0

**Comment by davidjgonzalez** [comment]
https://github.com/adobe/asset-share-commons/releases/tag/asset-share-commons-3.4.0
