### ISSUE TITLE
Multi-date filters are not working as expected.

### ISSUE THREAD

**Issue by bhumika528** [adobe/asset-share-commons#915]
In our project, we are using date- range filter i.e. Created date and Modified date.
If I give only Created date or Modification date the assets were filtering absolutely fine.
But the issue when I try to give both Modification and Created dates the assets were not filtering.
For example:
Created date:  From date: 2021-10-7
                           To date:2021-10-7T23:59:59
```
4_group.daterange.property=jcr%3Acreated
4_group.daterange.lowerBound=2021-10-7
4_group.daterange.upperBound=2021-10-7T23%3A59%3A59
```

This above query is working absolutely fine.

Modification date:  From date: 2021-10-7
                           To date:2021-10-7T23:59:59

```2_group.daterange.property=.%2Fjcr%3Acontent%2Fjcr%3AlastModified
2_group.daterange.lowerBound=2021-10-7
2_group.daterange.upperBound=2021-10-7T23%3A59%3A59
```

This above query is also working absolutely fine.

When I tried this combination of filters at the same time. expected results were not showing.

```
1_group.daterange.property=.%2Fjcr%3Acreated
1_group.daterange.lowerBound=2021-10-7
1_group.daterange.upperBound=2021-10-7
2_group.daterange.property=.%2Fjcr%3Acontent%2Fjcr%3AlastModified
2_group.daterange.lowerBound=2023-4-5
2_group.daterange.upperBound=2023-4-5T23%3A59%3A59
layout=card
p.offset=0
```

This is the query of combination of both the filters and as you can see the timestamp of upper bound value of created filter is missing.

**Comment by bhumika528** [comment]
Hi @davidjgonzalez, need your inputs on this issue

**Comment by bhumika528** [comment]
Hi @davidjgonzalez, can you please provide your inputs on this issue

**Comment by bhumika528** [comment]
Hi all, can anyone please help on this issue.

**Comment by davidjgonzalez** [comment]
v3.2.0 is out - please re-open if you continue to see issues.

**Comment by bhumika528** [comment]
Thank you @davidjgonzalez  for the response. Will check and get back to you if the bug still exists.

**Comment by davidjgonzalez** [comment]
Thanks!! Please do!
