### ISSUE TITLE
Share component is not formating the email address correctly and giving an error

### ISSUE THREAD

**Issue by MounicaTavanampalli93** [adobe/asset-share-commons#924]
Hi,

We have a site running and are using the share component, this has been working until recently, now it is throwing the following error in the logs and it appears that the email address is not formatted correctly.

2023-04-18 13:42:15.426 WARN [com.adobe.aem.commons.assetshare.util.impl.EmailServiceImpl] Invalid email address `mounica.tavanampalli&amp;#64;example.com` passed to sendEmail(). Skipping.

```
18.04.2023 13:42:15.427 [cm-p23459-e66250-aem-publish-cbd9775f6-pqvrv] *WARN* [168.149.246.61 [1681825335406] POST /content/example/us/en/actions/share/_jcr_content/root/responsivegrid/share.share.html HTTP/1.1] com.adobe.granite.metrics.knownerrors.impl.ErrorLoggingComponentFilter Exception in component: category=CUSTOMER_CODE, resourceType=roost/components/modals/share, exceptionType=java.lang.IllegalArgumentException, errorId=CUSTOMER, resource=/content/example/us/en/actions/share/jcr:content/root/responsivegrid/share, exceptionMessage = Invalid Recipients
18.04.2023 13:42:15.429 [cm-p23459-e66250-aem-publish-cbd9775f6-pqvrv] *ERROR* [168.149.246.61 [1681825335406] POST /content/example/us/en/actions/share/_jcr_content/root/responsivegrid/share.share.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.IllegalArgumentException: Invalid Recipients
```

We saw the issue after upgrading the AEM cloud version to 2023.3.11382.20230315T073850Z, before that it was working fine. And also tried by upgrading the ACS Commons version from 2.4.8 to 2.5.4. But the issue still persists.
We are currently using ACS Commoms version 2.5.4 and AEM SDK cloud version 2023.3.11382.20230315T073850Z.

Please provide suggestions to fix the issue. Its impacting major users.

Regards
Mounica

**Comment by davidjgonzalez** [comment]
Just to be clear, you upgrading to Asset Share Commons 2.5.4 (not ACS commons right? i know confusing name ;)) 

This seemed to be fixed in Asset Share Commons 2.5.4 (https://github.com/adobe/asset-share-commons/issues/908) but maybe something in latest AEM CS is re-breaking this.  Ill try to preproduce.

**Comment by MounicaTavanampalli93** [comment]
> Just to be clear, you upgrading to Asset Share Commons 2.5.4 (not ACS commons right? i know confusing name ;))
> 
> This seemed to be fixed in Asset Share Commons 2.5.4 (#908) but maybe something in latest AEM CS is re-breaking this. Ill try to preproduce.

**Comment by MounicaTavanampalli93** [comment]
Yes, I was mentioning Asset Share Commons Version

**Comment by davidjgonzalez** [comment]
Just double checking - this doesnt work on ASC 2.5.4? Im trying this out on 2023.3.11382.20230315 .. and its working with 2.5.4.

If i provide you with an updated bundle, could you test it out?

**Comment by davidjgonzalez** [comment]
@MounicaTavanampalli93 so i cannot re-produce this on 2023.3.11332.20230305T153954Z with ASC 2.5.4.

Can you triple check youre on ASC 2.5.4 Core bundle? (can you screenshot me where it says thats whats running in AEM CS?  And make sure thats the only Core bundle? There should be a Core and a Core Fragment bundles, but just 1 of each.

I've added some debug logging into this jar file that prints out the email addresses, so if you can install that  on your AME CS, and if we can see the logs showing the mangled emails that would be helpful to confirm your CS is infact acting differently than mine w/ the same version and same ASC codebase.

[assetshare.core-2.5.5-SNAPSHOT.renametojar.txt](https://github.com/adobe/asset-share-commons/files/11266917/assetshare.core-2.5.5-SNAPSHOT.renametojar.txt)

**Comment by MounicaTavanampalli93** [comment]
@davidjgonzalez I checked on ASC 2.5.4 Core bundle and as I mentioned earlier we are currently with ASC 2.5.4.

Attached the screenshot of AEM CS. Also, I cross checked and we are using one asset share core bundle.

<img width="1367" alt="Screen Shot 2023-04-19 at 1 05 39 PM" src="https://user-images.githubusercontent.com/131179758/233149599-4a3dc606-1b3a-460f-b8dc-8b40f6d0ca9c.png">

I am currently trying to set up the RDE. Will update you the status after checking.

Regards,
Mounica

**Comment by davidjgonzalez** [comment]
Can you also let me know what RDE youre testing it on? Just to make sure were in sync.

**Comment by MounicaTavanampalli93** [comment]
@davidjgonzalez , This looks like our project code issue. I figured it out after debugging the issue in AEM CS RDE.
Thank you very much for your quick response.

Regards,
Mounica

**Comment by davidjgonzalez** [comment]
Ok - thanks for letting us know @MounicaTavanampalli93
