### ISSUE TITLE
Asset Kits Pages root path incorrect property name

### ISSUE THREAD

**Issue by aguacatedan** [adobe/asset-share-commons#941]
**Describe the bug**
The property name in the Asset Kits workflow dialog is "ROOT_PATH_PATH" but the code is looking for "ROOT_PAGE_PATH". This results in the value set in the dialog being ignored and the workflow always using the default path "/content/asset-kits".

**Environment**
* AEM Version: AEMaaCS
* Asset Share Commons Version: 2.6.2
* Author

**To Reproduce**
1. Create an asset kits workflow
2. Set the Asset Kits Pages root path to something else like "/content/foobar"
3. Run the workflow with any payload
4. The page is created under /content/asset-kits

**Expected behavior**
Page should be created under /content/foobar

https://github.com/adobe/asset-share-commons/blob/fd844efb080fa53294de35028deda00241f716d6/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/workflow/asset-kit/asset-kit-creator/_cq_dialog/.content.xml#LL57C86-L57C86

**Comment by davidjgonzalez** [comment]
Fixed and released in v2.6.4 as we speak! Should be out in a 15-30mins (or however long it takes for Maven central to propegate)
