### ISSUE TITLE
Unable to preview pptx and docx files in AEM Digital Library

### ISSUE THREAD

**Issue by Sage-SA** [adobe/asset-share-commons#975]
Hi, 

I am having issue with previewing pptx and docx files in ASC. I have already added the PDF Viewer component to the page template but still getting an error message when trying to preview the file. PDF files are working fine.

Can you please help me if there is any additional configuration I have to do.

Thanks,
Sara
![Screenshot](https://github.com/adobe/asset-share-commons/assets/135127849/9ccaccc4-3ffa-4b54-9a51-a1b5f850dd7d)

**Comment by davidjgonzalez** [comment]
Hi!

How exactly are you trying to preview office documents? OOTB we just display their web image rendition. To get a interactive preview  that lets you page through, you'd need to embed a viewer like you are doing w PDF.

**Comment by Sage-SA** [comment]
The web image rendition is what I need and even though it's OOTB, it's not working.

**Comment by davidjgonzalez** [comment]
Have you double checked the web rendition has been created for the documents? If so, what are the rendition node names?

**Comment by davidjgonzalez** [comment]
@Sage-SA any luck looking into this?

**Comment by davidjgonzalez** [comment]
Please re-open if needed
