### ISSUE TITLE
Specific missing image based on filetype.

### ISSUE THREAD

**Issue by RahulMohann** [adobe/asset-share-commons#998]
Hi,

I know there is a missingImage feature that can be used as a common thumbnail for all assets that doesn't have 319.319 rendition. Is there a way where we can use specific missing image based on the file type? For example, for a zip file, we need to show zip.png as the missing thumbnail where as for a docx file, we need to show docximg.png as missing thumnail image.

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
Is this for the downloads or displaying on web page?

If on a web page, you could always make a new custom computed property that looks like (or even overrides w/ a higher service ranking) [1]  .. that determines if the rendition youtre trying to load exists, and if not, shows whatever fallback image based on your customer logic.

[1] https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/AssetRenditionImpl.java

**Comment by RahulMohann** [comment]
We managed to add a custom rendition '319.319' to all zip assets with the help of a scheduled workflow. And now that custom rendition is displayed as a thumbnail in ASC.
